In [1]:
import pandas as pd
from queries import *

C:\Users\smaxbehr\AppData\Local\anaconda3\envs\testenv\lib\site-packages\thinc\neural\train.py:7: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from .optimizers import Adam, linear_decay
C:\Users\smaxbehr\AppData\Local\anaconda3\envs\testenv\lib\site-packages\thinc\check.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Sequence, Sized, Iterable, Callable
C:\Users\smaxbehr\AppData\Local\anaconda3\envs\testenv\lib\site-packages\plac_ext.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
C:\Users\smaxbehr\AppData\Local\anaconda3\envs\testenv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
#load the ontology from "./ontologies/" and perform reasoning
onto_name= "afo_new_bascat_50pubs-2024-09-20" #input name of the ontology

#perform reasoning, get dois from publications in the extended ontology
onto_pub_list,onto,df=reasoning_dois_onto(onto_name)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
 
display(df)

* Owlready2 * WARNING: DataProperty http://xmlns.com/foaf/0.1/name belongs to more than one entity types: [owl.AnnotationProperty, owl.DatatypeProperty]; I'm trying to fix it...
* Owlready2 * Running HermiT...
    java -Xmx2000M -cp C:\Users\smaxbehr\AppData\Local\anaconda3\envs\testenv\lib\site-packages\owlready2\hermit;C:\Users\smaxbehr\AppData\Local\anaconda3\envs\testenv\lib\site-packages\owlready2\hermit\HermiT.jar org.semanticweb.HermiT.cli.CommandLine -c -O -D -I file:///C:/Users/smaxbehr/AppData/Local/Temp/tmpoeysdai_
* Owlready2 * HermiT took 446.0828764438629 seconds
* Owlready * Reparenting obo.BFO_0000118: {owl.TransitiveProperty, obo.BFO_0000117, owl.ObjectProperty, property.AFX_0002793} => {obo.BFO_0000117, property.AFX_0002793}
* Owlready * Reparenting property.AFX_0002724: {property.AFX_0002723, owl.ObjectProperty} => {property.AFX_0002723}
* Owlready * Reparenting property.AFX_0002816: {property.AFX_0002699, owl.ObjectProperty} => {property.AFX_0002699}
* Owlready * Reparenting obo.RO_0002216: {obo.RO_0002328, obo.RO_0002500, owl.ObjectProperty} => {obo.RO_0002328, obo.RO_0002500}
* Owlready * Reparenting obo.RO_0002264: {obo.RO_0002500, owl.ObjectProperty} => {obo.RO_0002500}
* Owlready * Reparenting obo.RO_0002405: {obo.RO_0002087, obo.RO_0002404, owl.ObjectProperty} => {obo.RO_0002087, obo.RO_0002404}
* Owlready * Reparenting property.AFX_0002833: {owl.TransitiveProperty, property.AFX_0002858, owl.ObjectProperty} => {property.AFX_0002858, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002516: {owl.TransitiveProperty, obo.RO_0002524, owl.ObjectProperty} => {obo.RO_0002524, obo.RO_0002525}
* Owlready * Reparenting property.AFX_0000561: {owl.ObjectProperty, property.AFX_0000314} => {property.AFX_0000314}
* Owlready * Reparenting property.AFX_0000560: {owl.ObjectProperty, property.AFX_0000314} => {property.AFX_0000314}
* Owlready * Reparenting obo.RO_0002220: {obo.RO_0002163, owl.ObjectProperty} => {obo.RO_0002163}
* Owlready * Reparenting property.AFX_0002717: {obo.IAO_0000219, owl.ObjectProperty} => {obo.IAO_0000219}
* Owlready * Reparenting property.AFX_0000974: {owl.TransitiveProperty, property.AFX_0000972, owl.ObjectProperty} => {property.AFX_0000972}
* Owlready * Reparenting property.AFX_0002748: {property.AFX_0000399, owl.ObjectProperty} => {property.AFX_0000399}
* Owlready * Reparenting obo.RO_0002229: {obo.RO_0002222, obo.BFO_0000050, owl.ObjectProperty} => {obo.RO_0002222, obo.BFO_0000050}
* Owlready * Reparenting obo.RO_0002012: {obo.BFO_0000050, owl.ObjectProperty, obo.RO_0002418} => {obo.BFO_0000050, obo.RO_0002418}
* Owlready * Reparenting obo.RO_0002223: {obo.RO_0002222, obo.BFO_0000050, owl.ObjectProperty} => {obo.RO_0002222, obo.BFO_0000050}
* Owlready * Reparenting obo.BFO_0000184: {obo.BFO_0000066, owl.InverseFunctionalProperty, owl.ObjectProperty} => {obo.BFO_0000066, owl.InverseFunctionalProperty}
* Owlready * Reparenting property.AFX_0002684: {property.AFX_0002802, owl.ObjectProperty} => {property.AFX_0002802}
* Owlready * Reparenting property.AFX_0000834: {owl.ObjectProperty} => {property.AFX_0002802}
* Owlready * Reparenting property.AFX_0002725: {property.AFX_0002722, owl.ObjectProperty} => {property.AFX_0002722}
* Owlready * Reparenting obo.RO_0000087: {owl.ObjectProperty, obo.RO_0000053} => {obo.RO_0000053}
* Owlready * Reparenting obo.RO_0002570: {obo.RO_0002131, owl.ObjectProperty} => {obo.RO_0002131}
* Owlready * Reparenting obo.RO_0002526: {obo.RO_0002131, obo.RO_0002514, owl.ObjectProperty} => {obo.RO_0002514, obo.RO_0002131}
* Owlready * Reparenting obo.RO_0002379: {obo.RO_0002131, owl.ObjectProperty} => {obo.RO_0002131}
* Owlready * Reparenting obo.RO_0002509: {obo.RO_0002131, obo.RO_0002506, owl.ObjectProperty} => {obo.RO_0002506, obo.RO_0002131}
* Owlready * Reparenting obo.RO_0002327: {obo.RO_0002215, owl.ObjectProperty} => {obo.RO_0002215}
* Owlready * Reparenting core.related: {core.semanticRelation, owl.SymmetricProperty, owl.ObjectProperty} => {core.semanticRelation, owl.SymmetricProperty}
* Owlready * Reparenting core.narrowerTransitive: {core.semanticRelation, owl.TransitiveProperty, owl.ObjectProperty} => {core.semanticRelation, owl.TransitiveProperty}
* Owlready * Reparenting core.mappingRelation: {core.semanticRelation, owl.ObjectProperty} => {core.semanticRelation}
* Owlready * Reparenting property.AFX_0002878: {property.AFX_0002730, owl.ObjectProperty} => {property.AFX_0002730}
* Owlready * Reparenting obo.RO_0000052: {owl.ObjectProperty, obo.RO_0002314} => {obo.RO_0002314}
* Owlready * Reparenting obo.RO_0002505: {obo.RO_0000057, owl.ObjectProperty} => {obo.RO_0000057}
* Owlready * Reparenting property.AFX_0000399: {obo.RO_0000057, owl.ObjectProperty} => {obo.RO_0000057}
* Owlready * Reparenting property.AFX_0000197: {obo.RO_0000057, owl.ObjectProperty} => {obo.RO_0000057}
* Owlready * Reparenting obo.RO_0002218: {obo.RO_0000057, owl.ObjectProperty} => {obo.RO_0000057}
* Owlready * Reparenting property.AFX_0002745: {obo.RO_0000057, owl.ObjectProperty} => {obo.RO_0000057}
* Owlready * Reparenting property.AFX_0002750: {obo.RO_0000057, owl.ObjectProperty} => {obo.RO_0000057}
* Owlready * Reparenting obo.RO_0002332: {obo.RO_0000057, owl.ObjectProperty} => {obo.RO_0000057}
* Owlready * Reparenting property.AFX_0002690: {owl.ObjectProperty, property.AFX_0002684} => {property.AFX_0002684}
* Owlready * Reparenting property.AFX_0002718: {owl.ObjectProperty, property.AFX_0002684} => {property.AFX_0002684}
* Owlready * Reparenting obo.RO_0002085: {owl.TransitiveProperty, obo.RO_0002088, owl.ObjectProperty} => {obo.RO_0002084, obo.RO_0002088, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002083: {owl.TransitiveProperty, obo.RO_0002081, owl.ObjectProperty} => {obo.RO_0002081, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002082: {owl.TransitiveProperty, obo.RO_0002081, owl.ObjectProperty} => {obo.RO_0002081, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002305: {obo.RO_0002411, owl.ObjectProperty} => {obo.RO_0002411}
* Owlready * Reparenting obo.RO_0002304: {obo.RO_0002411, owl.ObjectProperty} => {obo.RO_0002411}
* Owlready * Reparenting obo.RO_0002461: {obo.RO_0000056, owl.ObjectProperty} => {obo.RO_0000056}
* Owlready * Reparenting property.AFX_0002864: {obo.RO_0000056, owl.ObjectProperty} => {obo.RO_0000056}
* Owlready * Reparenting obo.RO_0002217: {obo.RO_0000056, owl.ObjectProperty} => {obo.RO_0000056}
* Owlready * Reparenting obo.RO_0002462: {obo.RO_0002461, owl.ObjectProperty} => {obo.RO_0002461}
* Owlready * Reparenting obo.RO_0002463: {obo.RO_0002461, owl.ObjectProperty} => {obo.RO_0002461}
* Owlready * Reparenting obo.RO_0002531: {obo.RO_0002528, owl.ObjectProperty, obo.RO_0002515} => {obo.RO_0002528, obo.RO_0002515}
* Owlready * Reparenting property.AFX_0002734: {property.AFX_0000353, owl.ObjectProperty} => {property.AFX_0000353}
* Owlready * Reparenting property.AFX_0002735: {property.AFX_0000353, owl.ObjectProperty} => {property.AFX_0000353}
* Owlready * Reparenting property.AFX_0002687: {property.AFX_0002686, owl.ObjectProperty} => {property.AFX_0002686}
* Owlready * Reparenting property.AFX_0002689: {property.AFX_0002686, owl.ObjectProperty} => {property.AFX_0002686}
* Owlready * Reparenting property.AFX_0000072: {property.AFX_0002686, owl.ObjectProperty} => {property.AFX_0002686}
* Owlready * Reparenting property.AFX_0002688: {property.AFX_0002686, owl.ObjectProperty} => {property.AFX_0002686}
* Owlready * Reparenting obo.RO_0002607: {obo.RO_0002610, owl.ObjectProperty} => {obo.RO_0002610}
* Owlready * Reparenting property.AFX_0002731: {property.AFX_0000388, owl.ObjectProperty} => {property.AFX_0000388}
* Owlready * Reparenting property.AFX_0002842: {obo.IAO_0000136, owl.ObjectProperty} => {obo.IAO_0000136}
* Owlready * Reparenting obo.IAO_0000219: {obo.IAO_0000136, owl.ObjectProperty} => {obo.IAO_0000136}
* Owlready * Reparenting property.AFX_0002704: {obo.IAO_0000136, owl.ObjectProperty} => {obo.IAO_0000136}
* Owlready * Reparenting property.AFX_0000355: {obo.IAO_0000136, owl.ObjectProperty} => {obo.IAO_0000136}
* Owlready * Reparenting property.AFX_0000388: {obo.IAO_0000136, owl.ObjectProperty} => {obo.IAO_0000136}
* Owlready * Reparenting property.AFX_0002723: {owl.TransitiveProperty, obo.RO_0002609, owl.ObjectProperty} => {obo.RO_0002609, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002610: {obo.RO_0002609, owl.ObjectProperty} => {obo.RO_0002609}
* Owlready * Reparenting obo.RO_0002410: {obo.RO_0002609, owl.ObjectProperty} => {obo.RO_0002609}
* Owlready * Reparenting property.AFX_0000551: {obo.RO_0002351, owl.AsymmetricProperty, owl.ObjectProperty, owl.IrreflexiveProperty} => {obo.RO_0002351}
* Owlready * Reparenting obo.BFO_0000185: {obo.BFO_0000067, owl.InverseFunctionalProperty, owl.ObjectProperty} => {obo.BFO_0000067, owl.InverseFunctionalProperty}
* Owlready * Reparenting property.AFX_0002703: {obo.BFO_0000133, owl.ObjectProperty} => {obo.BFO_0000133}
* Owlready * Reparenting obo.RO_0002427: {obo.RO_0002501, owl.TransitiveProperty, owl.ObjectProperty} => {obo.RO_0002501}
* Owlready * Reparenting obo.RO_0002418: {obo.RO_0002501, owl.TransitiveProperty, owl.ObjectProperty} => {obo.RO_0002501}
* Owlready * Reparenting obo.RO_0002344: {obo.RO_0002337, owl.ObjectProperty} => {obo.RO_0002337}
* Owlready * Reparenting obo.RO_0002341: {obo.RO_0002337, owl.ObjectProperty} => {obo.RO_0002337}
* Owlready * Reparenting property.AFX_0002835: {property.AFX_0002833, owl.ObjectProperty} => {property.AFX_0002833}
* Owlready * Reparenting obo.RO_0002523: {owl.TransitiveProperty, obo.RO_0002514, owl.ObjectProperty} => {obo.RO_0002514, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002224: {owl.TransitiveProperty, obo.RO_0002222, owl.ObjectProperty, obo.BFO_0000051} => {obo.RO_0002222, obo.BFO_0000051}
* Owlready * Reparenting obo.RO_0002508: {owl.ObjectProperty, obo.RO_0002566} => {obo.BFO_0000051, obo.RO_0002566}
* Owlready * Reparenting property.AFX_0000940: {owl.ObjectProperty, obo.BFO_0000051} => {obo.BFO_0000051}
* Owlready * Reparenting obo.RO_0002180: {owl.ObjectProperty, obo.BFO_0000051} => {obo.BFO_0000051}
* Owlready * Reparenting property.AFX_0002686: {property.AFX_0002718, owl.ObjectProperty} => {property.AFX_0002718}
* Owlready * Reparenting core.exactMatch: {owl.SymmetricProperty, owl.TransitiveProperty, core.closeMatch, owl.ObjectProperty} => {core.closeMatch, owl.TransitiveProperty}
* Owlready * Reparenting obo.OBI_0000314: {owl.ObjectProperty, property.AFX_0002821} => {property.AFX_0002821}
* Owlready * Reparenting property.AFX_0000554: {property.AFX_0000354, owl.ObjectProperty} => {property.AFX_0000354}
* Owlready * Reparenting property.AFX_0001049: {obo.RO_0001025, owl.ObjectProperty} => {obo.RO_0001025}
* Owlready * Reparenting obo.RO_0002428: {obo.RO_0002263, obo.RO_0002431, owl.ObjectProperty} => {obo.RO_0002431, obo.RO_0002263}
* Owlready * Reparenting property.AFX_0002839: {property.AFX_0002837, owl.ObjectProperty} => {property.AFX_0002837}
* Owlready * Reparenting property.AFX_0002838: {property.AFX_0002837, owl.ObjectProperty} => {property.AFX_0002837}
* Owlready * Reparenting obo.RO_0002090: {obo.BFO_0000063, owl.ObjectProperty} => {obo.BFO_0000063}
* Owlready * Reparenting obo.RO_0002084: {obo.RO_0002222, owl.ObjectProperty} => {obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002089: {owl.TransitiveProperty, obo.RO_0002222, owl.ObjectProperty} => {obo.RO_0002222, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002081: {obo.RO_0002222, owl.ObjectProperty} => {obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002086: {owl.TransitiveProperty, obo.RO_0002222, owl.ObjectProperty} => {obo.RO_0002222, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002093: {obo.RO_0002222, owl.ObjectProperty} => {obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002515: {owl.ObjectProperty, obo.RO_0002527} => {obo.RO_0002527}
* Owlready * Reparenting obo.RO_0002213: {obo.RO_0002304, owl.ObjectProperty, obo.RO_0002211} => {obo.RO_0002304, obo.RO_0002211}
* Owlready * Reparenting obo.RO_0002263: {owl.ObjectProperty, obo.RO_0002264} => {obo.RO_0002264}
* Owlready * Reparenting obo.RO_0002431: {obo.RO_0002328, obo.RO_0002500, owl.ObjectProperty, obo.RO_0002264} => {obo.RO_0002328, obo.RO_0002264}
* Owlready * Reparenting obo.RO_0002326: {obo.RO_0002216, owl.ObjectProperty} => {obo.RO_0002216}
* Owlready * Reparenting obo.RO_0002215: {obo.RO_0002216, owl.ObjectProperty} => {obo.RO_0002216}
* Owlready * Reparenting obo.RO_0000079: {obo.RO_0000052, owl.ObjectProperty} => {obo.RO_0000052}
* Owlready * Reparenting obo.RO_0002170: {obo.RO_0002323, owl.ObjectProperty} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002150: {obo.RO_0002323, owl.ObjectProperty} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002131: {obo.RO_0002323, owl.ObjectProperty} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002177: {obo.RO_0002323, owl.ObjectProperty} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002176: {obo.RO_0002323, owl.ObjectProperty} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002163: {obo.RO_0002323, owl.ObjectProperty} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002002: {obo.RO_0002323, owl.ObjectProperty} => {obo.RO_0002323}
* Owlready * Reparenting property.AFX_0002722: {obo.RO_0002502, owl.TransitiveProperty, owl.ObjectProperty} => {obo.RO_0002502, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002503: {obo.RO_0002502, owl.ObjectProperty} => {obo.RO_0002502}
* Owlready * Reparenting obo.RO_0002314: {obo.RO_0002502, owl.ObjectProperty} => {obo.RO_0002502}
* Owlready * Reparenting obo.RO_0002584: {obo.RO_0002328, obo.RO_0002595, owl.ObjectProperty} => {obo.RO_0002328, obo.RO_0002595}
* Owlready * Reparenting property.AFX_0002696: {owl.ObjectProperty, property.AFX_0002803} => {property.AFX_0002803}
* Owlready * Reparenting property.AFX_0002801: {owl.ObjectProperty, property.AFX_0002803} => {property.AFX_0002803}
* Owlready * Reparenting obo.RO_0002331: {obo.RO_0002431, owl.ObjectProperty} => {obo.RO_0002431}
* Owlready * Reparenting property.AFX_0000558: {owl.ObjectProperty, property.AFX_0000331} => {property.AFX_0000331}
* Owlready * Reparenting property.AFX_0000557: {owl.ObjectProperty, property.AFX_0000331} => {property.AFX_0000331}
* Owlready * Reparenting obo.BFO_0000139: {owl.TransitiveProperty, owl.ObjectProperty, obo.BFO_0000132} => {obo.BFO_0000132}
* Owlready * Reparenting obo.BFO_0000062: {owl.TransitiveProperty, obo.RO_0002086, owl.ObjectProperty} => {obo.RO_0002086}
* Owlready * Reparenting obo.RO_0003304: {obo.RO_0003302, owl.ObjectProperty} => {obo.RO_0003302}
* Owlready * Reparenting obo.RO_0003303: {obo.RO_0003302, owl.ObjectProperty} => {obo.RO_0003302}
* Owlready * Reparenting obo.RO_0002335: {obo.RO_0002334, owl.ObjectProperty} => {obo.RO_0002334}
* Owlready * Reparenting obo.RO_0002336: {obo.RO_0002334, owl.ObjectProperty} => {obo.RO_0002334}
* Owlready * Reparenting obo.RO_0002430: {obo.RO_0002428, owl.ObjectProperty} => {obo.RO_0002428}
* Owlready * Reparenting obo.RO_0002429: {obo.RO_0002428, owl.ObjectProperty} => {obo.RO_0002428}
* Owlready * Reparenting obo.RO_0002351: {property.AFX_0002793, owl.AsymmetricProperty, owl.ObjectProperty, owl.IrreflexiveProperty} => {property.AFX_0002793, owl.AsymmetricProperty, owl.IrreflexiveProperty}
* Owlready * Reparenting property.AFX_0002803: {owl.TransitiveProperty, owl.ObjectProperty, property.AFX_0002793} => {property.AFX_0002793}
* Owlready * Reparenting obo.OBI_0000643: {owl.TransitiveProperty, owl.ObjectProperty, property.AFX_0002793} => {property.AFX_0002793}
* Owlready * Reparenting obo.RO_0002212: {obo.RO_0002305, owl.ObjectProperty, obo.RO_0002211} => {obo.RO_0002305, obo.RO_0002211}
* Owlready * Reparenting obo.RO_0002338: {obo.RO_0002344, owl.ObjectProperty} => {obo.RO_0002344}
* Owlready * Reparenting obo.RO_0002342: {obo.RO_0002344, owl.ObjectProperty} => {obo.RO_0002344}
* Owlready * Reparenting obo.RO_0002339: {obo.RO_0002344, owl.ObjectProperty} => {obo.RO_0002344}
* Owlready * Reparenting obo.RO_0002219: {obo.RO_0002220, owl.ObjectProperty} => {obo.RO_0002220}
* Owlready * Reparenting obo.RO_0002221: {obo.RO_0002220, owl.ObjectProperty} => {obo.RO_0002220}
* Owlready * Reparenting obo.RO_0002501: {owl.TransitiveProperty, obo.RO_0002410, owl.ObjectProperty} => {obo.RO_0002410, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002506: {obo.RO_0002410, owl.ObjectProperty} => {obo.RO_0002410}
* Owlready * Reparenting obo.RO_0002595: {obo.RO_0002410, owl.ObjectProperty} => {obo.RO_0002410}
* Owlready * Reparenting obo.RO_0003302: {obo.RO_0002410, owl.ObjectProperty} => {obo.RO_0002410}
* Owlready * Reparenting obo.RO_0002500: {obo.RO_0002595, owl.ObjectProperty} => {obo.RO_0002595}
* Owlready * Reparenting property.AFX_0001179: {obo.RO_0002170, owl.ObjectProperty} => {obo.RO_0002170}
* Owlready * Reparenting property.AFX_0001178: {obo.RO_0002170, owl.ObjectProperty} => {obo.RO_0002170}
* Owlready * Reparenting property.AFX_0000546: {property.AFX_0000395, owl.ObjectProperty} => {property.AFX_0000395}
* Owlready * Reparenting obo.RO_0002559: {obo.RO_0002506, owl.ObjectProperty} => {obo.RO_0002506}
* Owlready * Reparenting core.broader: {core.broaderTransitive, owl.ObjectProperty} => {core.broaderTransitive}
* Owlready * Reparenting property.AFX_0000939: {owl.TransitiveProperty, property.AFX_0002846, owl.ObjectProperty} => {property.AFX_0002846}
* Owlready * Reparenting property.AFX_0002845: {property.AFX_0002846, owl.ObjectProperty} => {property.AFX_0002846}
* Owlready * Reparenting obo.OBI_0000645: {owl.TransitiveProperty, property.AFX_0002846, owl.ObjectProperty} => {property.AFX_0002846}
* Owlready * Reparenting obo.RO_0002350: {property.AFX_0002846, owl.AsymmetricProperty, owl.ObjectProperty, owl.IrreflexiveProperty} => {property.AFX_0002846, owl.AsymmetricProperty, owl.IrreflexiveProperty}
* Owlready * Reparenting obo.RO_0002087: {obo.BFO_0000062, owl.ObjectProperty} => {obo.BFO_0000062}
* Owlready * Reparenting property.AFX_0002862: {owl.DatatypeProperty, property.AFX_0000675} => {property.AFX_0000675}
* Owlready * Reparenting property.AFX_0000675: {property.AFX_0000674, owl.DatatypeProperty} => {property.AFX_0000674}
* Owlready * Reparenting property.AFX_0000676: {property.AFX_0000674, owl.DatatypeProperty} => {property.AFX_0000674}
* Owlready * Reparenting property.AFX_0002861: {owl.DatatypeProperty, property.AFX_0000671} => {property.AFX_0000671}
* Owlready * Reparenting property.AFX_0000671: {owl.DatatypeProperty, property.AFX_0000670} => {property.AFX_0000670}
* Owlready * Reparenting property.AFX_0000672: {owl.DatatypeProperty, property.AFX_0000670} => {property.AFX_0000670}
* Owlready * Reparenting property.AFX_0001198: {property.AFX_0000604, owl.DatatypeProperty} => {property.AFX_0000604}
* Owlready * Reparenting property.AFX_0001732: {property.AFX_0000690, owl.DatatypeProperty} => {property.AFX_0000690}
* Owlready * (NB: only changes on entities loaded in Python are shown, other changes are done but not listed)

The afo_new_bascat_50pubs-2024-09-20 ontology consists of following publications:

,DOI,Title
0,10.1016/j.apcata.2024.119636,Using CoCu2Ga/SiO2 to identify stability-issues in ethanol-selective Co-Cu alloyed catalysts in carbon monoxide hydrogenation
1,10.1016/j.cej.2024.152502,The active pair of Coδ+/Co0 tailored by nickel and CaTiO3 with perovskite phase for higher alcohols synthesis from syngas
2,10.1038/s41467-024-50215-1,Active learning streamlines development of high performance catalysts for higher alcohol synthesis
3,10.1002/anie.202401568,"Enhanced Proximity of Rh1,2-Rhn Ensembles Encaged in UiO-67 Boosting Catalytic Conversion of Syngas to Oxygenates"
4,10.1007/s10562-023-04565-y,A First Principles Mechanistic Study of Higher Alcohol Synthesis from Syngas on a Stepped Rhodium Surface
5,10.1016/j.apcatb.2023.122840,Hydrophobic dual metal silicate nanotubes for higher alcohol synthesis
6,10.31635/ccschem.022.202201930,Construction of Synergistic Co and Cu Diatomic Sites for Enhanced Higher Alcohol Synthesis
7,10.1016/j.fuel.2023.129772,Influence of chalcopyrite removal and mechanical exfoliation on the performance of molybdenite catalysts supported on activated bauxite for alcohol synthesis by Fischer-Tropsch process
8,10.3390/catal13020237,A Simple Strategy Stabilizing for a CuFe/SiO2 Catalyst and Boosting Higher Alcohols’ Synthesis from Syngas
9,10.1016/j.cej.2023.142359,CoMn catalysts derived from partial decomposed layered CoMn-MOF materials for higher alcohol synthesis from syngas
10,10.1021/acscatal.3c02534,"ZrO2-Promoted Cu-Co, Cu-Fe and Co-Fe Catalysts for Higher Alcohol Synthesis"
11,10.1021/acscatal.3c01577,Efficient Conversion of Syngas into Ethanol by Tandem Catalysis
12,10.1038/s41467-023-42325-z,Edge-rich molybdenum disulfide tailors carbon-chain growth for selective hydrogenation of carbon monoxide to higher alcohols
13,10.1021/acscatal.3c05351,Promotion of Anatase/Rutile Junction to Direct Conversion of Syngas to Ethanol on the Rh/TiO2 Catalysts
14,10.1016/j.fuel.2022.126308,CO hydrogenation to ethanol and higher alcohols over ultrathin CuCoAl nanosheets derived from LDH precursor
15,10.1016/j.checat.2023.100584,Precisely synergistic synthesis of higher alcohols from syngas over iron carbides
16,10.1016/j.poly.2022.116031,Competing mechanisms of CO hydrogenation to ethanol over TM/Mo6S8 catalysts
17,10.1021/acs.energyfuels.4c00590,Higher Alcohol and Oxygenate Synthesis from Synthesis Gas and Ethanol over Supported K-(Co)MoS2 Catalysts: Effect of Novel Ni-Containing Carbon Nanofiber Supports Formed as Byproducts from Methane Decomposition
18,10.1016/j.fuel.2022.126770,Synergetic effect of Ce/Zr for ethanol synthesis from syngas over Rh-based catalyst
19,10.1016/j.mcat.2024.114124,Ratio screening of high performance Rh-Ni catalyst for ethanol synthesis from syngas: An integration of theoretical and experimental investigation
20,10.1016/j.fuel.2021.122981,Direct conversion of syngas to ethanol over Rh-based and Cu-based tandem catalyst: Effect of Cu crystal plane
21,10.1021/acscatal.3c03488,Oxygen Vacancy over CoMnOx Catalysts Boosts Selective Ethanol Production in the Higher Alcohol Synthesis from Syngas
22,10.1021/acsanm.3c00109,Active Site Synergy of Rh and Co Derived from ZrO2-Supported LaRhxCo1-xO3 Perovskite Nanostructures for the Direct Synthesis of Ethanol from Syngas
23,10.1016/j.fuel.2023.128506,Oxygen vacancy regulation of microenviroment of Cu/ZnO catalyst for syngas conversion
24,10.1021/acs.jpcc.3c01827,CuZnAl@S-1 Catalyst for the Synthesis of Higher Alcohols by CO Hydrogenation
25,10.1021/acscatal.2c02103,Nature and Dynamic Evolution of Rh Single Atoms Trapped by CeO2in CO Hydrogenation
26,10.1016/j.fuproc.2022.107510,Effect of ZnO morphology on the performance of CuZnAl slurry catalysts for the ethanol synthesis from syngas
27,10.1002/cctc.202201104,Silica-supported Catalyst System Rh−Mn−Ir−Li−Ti in Syngas to Ethanol Reaction: Reactivity Trends and Performance Optimization
28,10.1016/j.gee.2021.06.001,The newly-assisted catalytic mechanism of surface hydroxyl species performed as the promoter in syngas-to-C2 species on the Cu-based bimetallic catalysts
29,10.1016/j.apsusc.2023.157330,Constructing the active pairs of Co0-Co2+ via surface solid reaction on TiO2 with the additives of La and Al for higher alcohols synthesis
30,10.1021/acscatal.3c02649,Regulating Oxygen Vacancies for Enhanced Higher Oxygenate Synthesis via Syngas
31,10.1016/j.fuel.2024.130915,Ordered mesoporous Mg-modified silica to confine MoS2 slabs with high sulfidation and dispersion for higher alcohol synthesis via CO hydrogenation
32,10.1039/d4ta01179a,Co-Co2C catalysts supported on carbon-coated ordered mesoporous silica with promoted CO insertion and C-C coupling for higher alcohol synthesis from syngas
33,10.1016/j.cej.2024.148751,Lignin carbon-initiated Ni/K/Mo2C catalyst for efficient synthesis of higher alcohols from syngas
34,10.1016/j.fuel.2023.130595,Investigation of the role of oxygen vacancies in CuZn catalysts for the formation of higher alcohols from syngas
35,10.1016/j.apcatb.2021.120739,Design of efficient ZnO/ZrO2 modified CuCoAl catalysts for boosting higher alcohol synthesis in syngas conversion
36,10.1016/j.ijhydene.2023.12.292,Tuning CuO crystallite size by different solvents for higher alcohols synthesis from syngas over CuZnAl catalyst
37,10.1016/j.apcata.2024.119822,Impact of Cu complex anions on CuZnAl intercalated hydrotalcite-like catalysts for low-carbon alcohols synthesis from syngas
38,10.1021/acscatal.3c00363,Maximizing the Interface of Dual Active Sites to Enhance Higher Oxygenate Synthesis from Syngas with High Activity
39,10.1021/ie502425d,Direct conversion of syngas-to-hydrocarbons over higher alcohols synthesis catalysts mixed with HZSM-5
40,10.1016/j.fuel.2023.127500,Higher alcohols synthesis via Fischer–Tropsch reaction at hcp-Co@Co2C interface
41,10.1016/j.fuproc.2022.107600,Electronic control of catalytic activity of ZnO for higher alcohols synthesis via tailoring Fermi level
42,10.1021/acs.iecr.3c02379,LaAlO3-Tailored Active Pairs of Co0-Coδ+ Supported on ZrO2 for Higher Alcohol Synthesis from Syngas
43,10.1016/j.checat.2024.101010,Defective zirconia promotes monometallic iron catalysts for higher alcohol synthesis
44,10.1016/j.apsusc.2021.151846,Oxygen vacancies boosted Co-Co2C catalysts for higher alcohols synthesis from syngas
45,10.1016/j.ijhydene.2024.05.362,Novel designing concept of CoCu catalyst with limited methanol formation in higher alcohol synthesis from syngas
46,10.1016/j.mcat.2023.113421,2D h-BN material covered Cu confined catalysts: unraveling the function of spatial dimension in tuning activity and selectivity of syngas-to-C2 oxygenates
47,10.1021/acscatal.3c05579,Zinc Blende CoO as an Efficient CO Nondissociative Adsorption Site for Direct Synthesis of Higher Alcohols from Syngas
48,10.1016/j.mcat.2023.113270,Cerium doped Co/AC catalysts for higher alcohols synthesis from syngas

define DOI if only publications similar to specific publication in ontology should be queried from scopus\
if all publications in ontology should be used for query define the variable as:\
`doi = None`

In [ ]:
doi = r'10.1016/j.fuel.2023.127500'

Retrieve an abstract of the specific publication in the ontology given the DOI of the publication

In [ ]:
doi_1=r'10.1016/j.checat.2023.100584'
abstract=get_abstr(doi_1)

Following cells represent possible queries for reactions

- get list of all reactions for corresponding doi or from all publications if doi=None

In [ ]:
list_reac_doi,_ = get_reaction(reac=None,doi=doi,include_all=False) #doi=None (if from all publications)
reac_all = [*set([i[0].lower() for i in list_reac_doi])]
print(reac_all)

- get the list of all publications in ontology where same reactions as in input publication were mentioned

In [ ]:
list_reac_doi,_ = get_reaction(reac = None,doi = doi) #get list of all reactions mentioned in given doi (doi should be part of ontology)
same_reac_doi = []
for i in list_reac_doi:
    reac_doi,_ = get_reaction(reac = i[0],doi = None)
    for c in reac_doi:
        if c not in same_reac_doi and c[0] != doi:
            same_reac_doi.append(c)     #output example: [['10.1016/0304-5102(93)87113-m'],['10.1016/1381-1169(96)00243-9']]

print(list_reac_doi)
print(same_reac_doi)

- get the list of publications, that mention the specific reaction

In [ ]:
reac="hydrogenation"
list_reac_doi,_ = get_reaction(reac=reac,doi=None)  #output example: [['10.1016/0304-5102(93)87113-m'],['10.1016/1381-1169(96)00243-9']]
print(list_reac_doi)

- get list of all publications which mention the specific reaction and reactions which have this specific reaction as part of their label

In [ ]:
reac="hydroformylation" #specify a reaction

list_reac_doi, df_reac = get_reaction(reac="hydroformylation",doi=None, include_all=True)

display(df_reac)

- get list of all entities mentioned in specific publication

In [ ]:
list_ent=get_entList(list_type='all',entity= None,doi=doi)
print([i[1] for i in list_ent])

- get list of all extracted entities from publications in knowledge graph

In [ ]:
list_ent=[i[1] for i in get_entList(list_type='all',entity= None,doi=None)]
list_distinct=[]
for i in list_ent:
    if i not in list_distinct:
        list_distinct.append(i)
print(list_distinct)

In [ ]:
doi=None

In [ ]:
doi = "10.1021/acscatal.3c05579"

With following code the retrieval if all reactants, products, support materials, catalysts is performed, which are mentioned in one specific publication or from all publication in extended ontology (if doi=None) 
with `get_synonyms` all possible synonyms of chemical entities will be retrieved.\
For example from "rhodium atom " class, synonyms such as "Rh", "rhodium", "45Rh" are retrieved

In [ ]:
sup_list=get_support(sup=None,doi=doi)
_,sup_all=get_synonyms(sup_list)
print('all queried synonyms of support:')
print(list(sup_all.values()))

cat_list=get_catalyst(cat=None,doi=doi,include_all=True)
_,cat_all=get_synonyms(cat_list)
print('\nall queried synonyms of catalytic components:')
print(list(cat_all.values()))

reactant_list=get_entList('reactant',entity= None,doi=doi)
reactant_all,_=get_synonyms(reactant_list)
print('\nall queried synonyms of reactants:')
print(reactant_all)

product_list=get_entList('product',entity= None,doi=doi)
product_all,_=get_synonyms(product_list)
print('\nall queried synonyms of products:')
print(product_all)

cat_list_full=get_catalyst_full(doi = doi)
_,cat_full_all=get_synonyms(cat_list_full)
print('\nall queried catalyst entities:')
print(list(cat_full_all.values()))

### Iterate through all DOIs

In [3]:
def pad_list(data, target_len):
    #data_new = [x for x in data if onto_name not in x]
    data_new = [item for sublist in data for item in sublist if type(item) ==str]
    return list(set(data_new)) + [None] * (target_len - len(list(set(data_new))))

def list_len(data):
    data_new = [item for sublist in data for item in sublist if type(item) ==str]
    return len(list(set(data_new)))

df_all = pd.DataFrame()

for doi in df["DOI"]:

    if doi != "10.1016/j.mcat.2023.11327":

        sup_list=get_support(sup=None,doi=doi)
        _,sup_all=get_synonyms(sup_list)
        #  print('all queried synonyms of support:')
        #print(list(sup_all.values()))

        cat_list=get_catalyst(cat=None,doi=doi,include_all=True)
        _,cat_all=get_synonyms(cat_list)
        #  print('\nall queried synonyms of catalytic components:')
        #print(list(cat_all.values()))

        reactant_list=get_entList('reactant',entity= None,doi=doi)
        reactant_all,_=get_synonyms(reactant_list)
        #  print('\nall queried synonyms of reactants:')
        #print(reactant_all)

        product_list=get_entList('product',entity= None,doi=doi)
        product_all,_=get_synonyms(product_list)
        #  print('\nall queried synonyms of products:')
        #print(product_all)

        cat_list_full=get_catalyst_full(doi = doi)
        _,cat_full_all=get_synonyms(cat_list_full)
        #  print('\nall queried catalyst entities:')
        #  print(list(cat_full_all.values()))

        #max_len = max(len(list(sup_all.values())), len(list(cat_all.values())), len(reactant_all), len(product_all), len(list(cat_full_all.values())))
        max_len = max(list_len(sup_list), list_len(cat_list), list_len(reactant_list), list_len(product_list), list_len(cat_list_full))

        doi_extended = [doi] * max_len
        sup_extended = pad_list(sup_list, max_len)
        cat_extended = pad_list(cat_list, max_len)
        reactant_extended = pad_list(reactant_list, max_len)
        product_extended = pad_list(product_list, max_len)
        cat_full_extended = pad_list(cat_list_full, max_len)
        
        if doi == '10.1016/j.apcata.2024.119636':
            cat_full_ext_stor = cat_full_extended
            cat_list_full_stor = cat_list_full
        
        #if cat_full_extended != []:
        #    data_new = [x for x in cat_full_extended if onto_name not in x]

        df_out = pd.DataFrame({
            'doi': doi_extended,
            'catalyst with carrier': cat_full_extended,
            'support': sup_extended,
            'catalytic component': cat_extended,
            'reactant': reactant_extended,
            'product': product_extended        
        })

        df_all = pd.concat([df_all, df_out], axis = 0)

df_all

,doi,catalyst with carrier,support,catalytic component,reactant,product
0,10.1016/j.apcata.2024.119636,CuCo intermetallic,silicon dioxide,CoCu2Ga,thermo-catalytic CO,hydrocarbon
1,10.1016/j.apcata.2024.119636,ternary-alloyed CoCu2Ga nanoparticle supported on silica,ternary-alloyed CoCu2Ga nanoparticle supported on silica,cobalt;copper,higher alcohol,higher alcohol
2,10.1016/j.apcata.2024.119636,None,None,silicon dioxide,ethanol,methane
3,10.1016/j.apcata.2024.119636,None,None,copper atom,carbon monoxide,ethanol
4,10.1016/j.apcata.2024.119636,None,None,cobalt atom,methanol,thermocatalytic ethanol
5,10.1016/j.apcata.2024.119636,None,None,None,None,methanol
0,10.1016/j.cej.2024.152502,CoNi bimetal supported on CaTiO3,calcium titanate,cobalt atom,higher alcohol,higher alcohol
1,10.1016/j.cej.2024.152502,None,CoNi bimetal supported on CaTiO3,nickel atom,carbon monoxide,alcohol
2,10.1016/j.cej.2024.152502,None,None,cobalt;nickel,None,Higher alcohol
3,10.1016/j.cej.2024.152502,None,None,Coδ+/Co0,None,None
0,10.1038/s41467-024-50215-1,Fe65Co19Cu5Zr11 catalyst,None,zirconium atom,carbon monoxide,carbon dioxide
1,10.1038/s41467-024-50215-1,FeCoCuZr catalyst,None,iron atom,None,alcohol
2,10.1038/s41467-024-50215-1,None,None,FeCoCuZr,None,methane
3,10.1038/s41467-024-50215-1,None,None,Fe65Co19Cu5Zr11,None,None
4,10.1038/s41467-024-50215-1,None,None,copper atom,None,None
5,10.1038/s41467-024-50215-1,None,None,cobalt atom,None,None
0,10.1002/anie.202401568,Monometallic Rh catalysts,None,rhodium atom,carbon monoxide,oxygenate
1,10.1002/anie.202401568,Rh catalysts,None,None,None,None
0,10.1007/s10562-023-04565-y,Rhodium catalyst,None,rhodium atom,higher alcohol,higher alcohol
1,10.1007/s10562-023-04565-y,None,None,None,ethanol,methane
2,10.1007/s10562-023-04565-y,None,None,None,carbon monoxide,methoxide
3,10.1007/s10562-023-04565-y,None,None,None,None,ethanol
0,10.1016/j.apcatb.2023.122840,None,None,copper atom,carbon monoxide,carbon dioxide
1,10.1016/j.apcatb.2023.122840,None,None,CuCoSNTs,None,alcohol
2,10.1016/j.apcatb.2023.122840,None,None,cobalt atom,None,None
0,10.31635/ccschem.022.202201930,Co supported on Cu-NC,None,copper atom,higher alcohol,higher alcohol
1,10.31635/ccschem.022.202201930,None,None,cobalt atom,carbon monoxide,alcohol
2,10.31635/ccschem.022.202201930,None,None,Cu1-N4,None,None
3,10.31635/ccschem.022.202201930,None,None,Cu-NC,None,None
0,10.1016/j.fuel.2023.129772,low-grade molybdenite concentrate,None,molybdenum disulfide,higher alcohol,higher alcohol
1,10.1016/j.fuel.2023.129772,None,None,mesoporous activated bauxite,carbon monoxide,C3+ alcohol
2,10.1016/j.fuel.2023.129772,None,None,catalyst based on impure molybdenite,None,alcohol
0,10.3390/catal13020237,CuFe supported on SiO2 catalyst,silicon dioxide,silicon dioxide,higher alcohol,hydrocarbon
1,10.3390/catal13020237,None,CuFe supported on SiO2 catalyst,copper;iron,direct CO,higher alcohol
2,10.3390/catal13020237,None,None,iron atom,carbon monoxide,total alcohol
3,10.3390/catal13020237,None,None,copper atom,None,alcohol
0,10.1016/j.cej.2023.142359,CoMn-350 catalyst,None,cobalt atom,higher alcohol,higher alcohol
1,10.1016/j.cej.2023.142359,None,None,manganese atom,carbon monoxide,alcohol
0,10.1021/acscatal.3c02534,Co1Fe4 supported on ZrO2-10,Co1Fe4 supported on ZrO2-10,zirconium atom,carbon monoxide,None
1,10.1021/acscatal.3c02534,ZrO2-free counterpart,ZrO2-free counterpart,iron atom,None,None
2,10.1021/acscatal.3c02534,Co-Fe m-FTS,dioxozirconium,cobalt;copper,None,None
3,10.1021/acscatal.3c02534,None,None,oxygen atom,None,None
4,10.1021/acscatal.3c02534,None,None,5-10 mol% ZrO2,None,None
5,10.1021/acscatal.3c02534,None,None,Cu1Co4,None,None
6,10.1021/acscatal.3c02534,None,None,cobalt;iron,None,None
7,10.1021/acscatal.3c02534,None,None,"Cu:Co = 1:4, 5 mol% ZrO2",None,None
8,10.1021/acscatal.3c02534,None,None,copper atom,None,None
9,10.1021/acscatal.3c02534,None,None,cobalt atom,None,None
10,10.1021/acscatal.3c02534,None,None,dioxozirconium,None,None
0,10.1021/acscatal.3c01577,CuZnAlOx supported on γ-Al2O3,None,Cu1Zn2AlOx,dimethyl ether,carbon dioxide
1,10.1021/acscatal.3c01577,None,None,oxygen atom,ethanol,ethanol
2,10.1021/acscatal.3c01577,None,None,aluminium atom,carbon monoxide,None
3,10.1021/acscatal.3c01577,None,None,CuZnAlOx,None,None
4,10.1021/acscatal.3c01577,None,None,copper atom,None,None
5,10.1021/acscatal.3c01577,None,None,γ-Al2O3,None,None
0,10.1038/s41467-023-42325-z,None,None,molybdenum disulfide,higher alcohol,higher alcohol
1,10.1038/s41467-023-42325-z,None,None,potassium atom,methanol,methanol
2,10.1038/s41467-023-42325-z,None,None,oxygen atom,carbon monoxide,C2-4OH
0,10.1021/acscatal.3c05351,Rh supported on the pure phase anatase or rutile TiO2,Rh supported on P25 catalyst,titanium dioxide,ethanol,cycloheximide
1,10.1021/acscatal.3c05351,Rh supported on TiO2 catalyst,Rh supported on the pure phase anatase or rutile TiO2,rhodium atom,carbon monoxide,ethanol
2,10.1021/acscatal.3c05351,None,titanium dioxide,None,None,None
3,10.1021/acscatal.3c05351,None,Rh supported on TiO2 catalyst,None,None,None
4,10.1021/acscatal.3c05351,None,supported single Rh catalyst,None,None,None
5,10.1021/acscatal.3c05351,None,rhodium atom,None,None,None
0,10.1016/j.fuel.2022.126308,CuCo-LDH-aw,None,copper atom,higher alcohol,higher alcohol
1,10.1016/j.fuel.2022.126308,None,None,cobalt atom,ethanol,ethanol
2,10.1016/j.fuel.2022.126308,None,None,CuCo-LDH,carbon monoxide,None
0,10.1016/j.checat.2023.100584,CaFe catalyst,None,iron atom,higher alcohol,higher alcohol
1,10.1016/j.checat.2023.100584,None,None,CaFe,carbon monoxide,alcohol
2,10.1016/j.checat.2023.100584,None,None,None,None,oxygenate
0,10.1016/j.poly.2022.116031,TM supported on Mo6S8 catalyst,None,Thr-Met,oxomethyl,methanol
1,10.1016/j.poly.2022.116031,"TM supported on Mo6S8 (TM = Fe, Ru) catalysts",None,ruthenium atom,methanol,methane
2,10.1016/j.poly.2022.116031,Fe supported on Mo6S8,None,Mo6S8,ethanol,ethanol
3,10.1016/j.poly.2022.116031,None,None,iron atom,carbon monoxide,oxygenate
4,10.1016/j.poly.2022.116031,None,None,None,None,acetaldehyde
5,10.1016/j.poly.2022.116031,None,None,None,None,ethane
0,10.1021/acs.energyfuels.4c00590,82Ni-8Cu supported on Al2O3 catalyst,molybdenum disulfide,molybdenum disulfide,higher alcohol,alcohol
1,10.1021/acs.energyfuels.4c00590,catalyst supported on Al2O3,catalyst supported on Al2O3,fabric-activated carbon,ethanol,higher alcohol
2,10.1021/acs.energyfuels.4c00590,None,aluminium oxide,aluminium oxide,None,methane
3,10.1021/acs.energyfuels.4c00590,None,unprompted (K)-MoS2 catalyst supported on CNF-82Ni-8Cu/Al2O3 (CNFS),copper atom,None,ethanol
4,10.1021/acs.energyfuels.4c00590,None,82Ni-8Cu supported on Al2O3 catalyst,carbon-coated alumina,None,oxygenate
5,10.1021/acs.energyfuels.4c00590,None,CNF-82Ni-8Cu/Al2O3,cobalt atom,None,None
0,10.1016/j.fuel.2022.126770,2.0Rh5.0Ce-ZrO2 catalyst,None,zirconium atom,ethanol,carbon dioxide
1,10.1016/j.fuel.2022.126770,None,None,Rh5.0Ce-ZrO2,None,methane
2,10.1016/j.fuel.2022.126770,None,None,oxygen atom,None,ethanol
3,10.1016/j.fuel.2022.126770,None,None,cerium,None,None
4,10.1016/j.fuel.2022.126770,None,None,rhodium atom,None,None
0,10.1016/j.mcat.2024.114124,1Rh1Ni supported on γ-Al2O3,None,Rh1Ni1(111),ethanol,ethanol
1,10.1016/j.mcat.2024.114124,Ni supported on γ-Al2O3,None,RhxNiy(111),None,None
2,10.1016/j.mcat.2024.114124,1Rh1Ni supported on γ-Al2O3 catalyst,None,oxygen atom,None,None
3,10.1016/j.mcat.2024.114124,None,None,aluminium atom,None,None
4,10.1016/j.mcat.2024.114124,None,None,nickel atom,None,None
5,10.1016/j.mcat.2024.114124,None,None,rhodium atom,None,None
6,10.1016/j.mcat.2024.114124,None,None,γ-Al2O3,None,None
0,10.1016/j.fuel.2021.122981,Rh supported on P25 and 18 facet Cu2O nc,None,copper atom,ethanol,ethanol
1,10.1016/j.fuel.2021.122981,Rh supported on P25 and different facet Cu2O nanocrystal,None,P25,None,None
2,10.1016/j.fuel.2021.122981,Rh-based and Cu nc catalysts,None,rhodium atom,None,None
3,10.1016/j.fuel.2021.122981,None,None,cuprous oxide,None,None
0,10.1021/acscatal.3c03488,None,None,untransformed CoxMn1-xO,ethanol,alcohol
1,10.1021/acscatal.3c03488,None,None,cobalt atom,None,short-chain alcohol
2,10.1021/acscatal.3c03488,None,None,manganese atom,None,Higher alcohol
3,10.1021/acscatal.3c03488,None,None,oxygen atom,None,ethanol
4,10.1021/acscatal.3c03488,None,None,None,None,C2-5OH
0,10.1021/acsanm.3c00109,None,La-RhCo supported on ZrO2 nanoscaled catalyst,zirconium atom,ethanol,ethanol
1,10.1021/acsanm.3c00109,None,dioxozirconium,oxygen atom,None,None
2,10.1021/acsanm.3c00109,None,None,cobalt;rhodium,None,None
3,10.1021/acsanm.3c00109,None,None,cobalt atom,None,None
4,10.1021/acsanm.3c00109,None,None,rhodium atom,None,None
5,10.1021/acsanm.3c00109,None,None,dioxozirconium,None,None
0,10.1016/j.fuel.2023.128506,Cu4 supported on ZnO(0001) catalyst,Cu4 supported on ZnO(0001),zinc oxide,oxomethyl,methanol
1,10.1016/j.fuel.2023.128506,Cu supported on ZnO catalyst,zinc oxide,1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide,methanol,ethanol
2,10.1016/j.fuel.2023.128506,Cu4 supported on ZnO(0001)-5%Ov,Cu4 supported on ZnO(0001) catalyst,copper atom,ethanol,None
3,10.1016/j.fuel.2023.128506,Cu4 supported on ZnO(0001),Cu supported on ZnO catalyst,None,None,None
4,10.1016/j.fuel.2023.128506,None,Cu4 supported on ZnO(0001)-5%Ov,None,None,None
5,10.1016/j.fuel.2023.128506,None,perfect and defective Cu4 supported on ZnO(0001) catalyst,None,None,None
0,10.1021/acs.jpcc.3c01827,ZnAl supported on S-1,None,copper;zinc,ethanol,ethanol
1,10.1021/acs.jpcc.3c01827,CuZn supported on S-1,None,ZnAl,None,None
2,10.1021/acs.jpcc.3c01827,CZA supported on S-1 catalyst,None,LSM-1306,None,None
3,10.1021/acs.jpcc.3c01827,CZA supported on S-1,None,aluminium atom,None,None
4,10.1021/acs.jpcc.3c01827,CuZnAl supported on S-1,None,aluminum;zinc;copper(1+),None,None
5,10.1021/acs.jpcc.3c01827,CuZnAl catalyst,None,S-1,None,None
6,10.1021/acs.jpcc.3c01827,CuAl supported on S-1,None,aluminum;copper,None,None
7,10.1021/acs.jpcc.3c01827,None,None,copper atom,None,None
0,10.1021/acscatal.2c02103,Rh supported on ceo2catalyst,None,ceo2catalyst,ethanol,ethanol
1,10.1021/acscatal.2c02103,Rh supported on CeO2SACs with different Rh loadings (0.2-4 wt% Rh,None,oxygen atom,None,None
2,10.1021/acscatal.2c02103,None,None,atomically dispersed Rh,None,None
3,10.1021/acscatal.2c02103,None,None,cerium,None,None
4,10.1021/acscatal.2c02103,None,None,CeO2SACs,None,None
5,10.1021/acscatal.2c02103,None,None,rhodium atom,None,None
0,10.1016/j.fuproc.2022.107510,CuZnAl catalyst,None,Flower-like ZnO,methanol,methanol
1,10.1016/j.fuproc.2022.107510,None,None,zinc oxide,ethanol,total alcohol
2,10.1016/j.fuproc.2022.107510,None,None,aluminium atom,None,alcohol
3,10.1016/j.fuproc.2022.107510,None,None,aluminum;zinc;copper(1+),None,ethanol
4,10.1016/j.fuproc.2022.107510,None,None,copper atom,None,None
0,10.1002/cctc.202201104,silica-supported catalyst,silicon dioxide,"Rh, 0.45Mn, 1.3Ir, 0.04Li",ethanol,ethanol
1,10.1002/cctc.202201104,Silica-supported catalyst based on Rh,silica-supported catalyst,iridium atom,None,None
2,10.1002/cctc.202201104,"2.8Rh, 0.45Mn, 1.3Ir, 0.04Li",Silica-supported catalyst based on Rh,silicon dioxide,None,None
3,10.1002/cctc.202201104,None,None,lithium atom,None,None
4,10.1002/cctc.202201104,None,None,"Ir, Li and Ti",None,None
5,10.1002/cctc.202201104,None,None,manganese atom,None,None
6,10.1002/cctc.202201104,None,None,rhodium atom,None,None
0,10.1016/j.gee.2021.06.001,"MCu (M = Co, Fe, Rh) catalysts",None,iron atom,methanol,hydrocarbon
1,10.1016/j.gee.2021.06.001,MCu catalysts,None,hydroxide,None,cycloheximide
2,10.1016/j.gee.2021.06.001,OH supported on MCu catalyst,None,copper atom,None,C2 hydrocarbon
3,10.1016/j.gee.2021.06.001,None,None,cobalt atom,None,oxygenate
4,10.1016/j.gee.2021.06.001,None,None,MCu,None,methanol
5,10.1016/j.gee.2021.06.001,None,None,rhodium atom,None,None
0,10.1016/j.apsusc.2023.157330,bare Co supported on TiO2 catalyst,titanium dioxide,lanthanum atom,higher alcohol,higher alcohol
1,10.1016/j.apsusc.2023.157330,None,Co-based catalyst supported on TiO2 modified by La and Al,cobalt(2+);oxido(oxo)alumane,None,total alcohol
2,10.1016/j.apsusc.2023.157330,None,bare Co supported on TiO2 catalyst,oxygen atom,None,alcohol
3,10.1016/j.apsusc.2023.157330,None,None,aluminium atom,None,None
4,10.1016/j.apsusc.2023.157330,None,None,titanium dioxide,None,None
5,10.1016/j.apsusc.2023.157330,None,None,Co metal-CoAl2O4,None,None
6,10.1016/j.apsusc.2023.157330,None,None,cobalt atom,None,None
0,10.1021/acscatal.3c02649,None,titanium dioxide,titanium dioxide,None,oxygenate
1,10.1021/acscatal.3c02649,None,rutile TiO2-supported catalyst,None,None,None
0,10.1016/j.fuel.2024.130915,KNiMoS supported on Mg-MS-20,None,molybdenum disulfide,None,alcohol
1,10.1016/j.fuel.2024.130915,KNiMoS catalysts,None,Mg-MS-20,None,None
2,10.1016/j.fuel.2024.130915,Mg-modified mesoporous silica (Mg-MS-x),None,ordered mesoporous silica confined KNiMoS,None,None
3,10.1016/j.fuel.2024.130915,None,None,Mg-MS-x,None,None
4,10.1016/j.fuel.2024.130915,None,None,silicon dioxide,None,None
5,10.1016/j.fuel.2024.130915,None,None,KNiMoS,None,None
6,10.1016/j.fuel.2024.130915,None,None,potassium atom,None,None
7,10.1016/j.fuel.2024.130915,None,None,nickel atom,None,None
0,10.1039/d4ta01179a,Co-Co2C catalyst,-,silicon dioxide,None,alcohol
1,10.1039/d4ta01179a,Co supported on xC supported on OMS,"(1-methylcyclobutyl) N-[(1S,4R,6S,7Z,14S,18R)-18-(7-methoxy-3-methylquinoxalin-2-yl)oxy-4-[(1-methylcyclopropyl)sulfonylcarbamoyl]-2,15-dioxo-3,16-diazatricyclo[14.3.0.04,6]nonadec-7-en-14-yl]carbamate",cobalt atom,None,None
2,10.1039/d4ta01179a,carbon-coated amorphous SiO2 supported sample,Co supported on xC supported on OMS,Co-Co2C,None,None
3,10.1039/d4ta01179a,carbon-silica composite support,carbon-coated amorphous SiO2 supported sample,None,None,None
4,10.1039/d4ta01179a,carbon-coated ordered mesoporous silica (OMS) supported cobalt catalyst,carbon-silica composite support,None,None,None
5,10.1039/d4ta01179a,Co supported on 10C supported on OMS,silicon dioxide,None,None,None
6,10.1039/d4ta01179a,None,carbon-coated ordered mesoporous silica (OMS) supported cobalt catalyst,None,None,None
7,10.1039/d4ta01179a,None,Co supported on 10C supported on OMS,None,None,None
8,10.1039/d4ta01179a,None,"sodium;4-[(Z)-[4-(ethylamino)-3-methylphenyl]-(4-ethylimino-3-methylcyclohexa-2,5-dien-1-ylidene)methyl]-3-sulfobenzenesulfonate",None,None,None
9,10.1039/d4ta01179a,None,cobalt atom,None,None,None
10,10.1039/d4ta01179a,None,carbon atom,None,None,None
0,10.1016/j.cej.2024.148751,carbide catalyst,None,porous nano molybdenum carbide,higher alcohol,higher alcohol
1,10.1016/j.cej.2024.148751,None,None,open mesoporous lignin carbon,None,alcohol
2,10.1016/j.cej.2024.148751,None,None,carbide,None,None
0,10.1016/j.fuel.2023.130595,CZ-0.80 catalyst,None,copper;zinc,coal,alcohol
1,10.1016/j.fuel.2023.130595,CuZn catalyst,None,iron atom,None,None
2,10.1016/j.fuel.2023.130595,None,None,electron-rich Cu,None,None
3,10.1016/j.fuel.2023.130595,None,None,CZ-0.80,None,None
4,10.1016/j.fuel.2023.130595,None,None,copper atom,None,None
5,10.1016/j.fuel.2023.130595,None,None,cobalt atom,None,None
0,10.1016/j.apcatb.2021.120739,CCA|ZnO|CCA|ZnO supported on ZrO2 catalyst,ZnO modified ZrO2 composite,zirconium atom,higher alcohol,higher alcohol
1,10.1016/j.apcatb.2021.120739,ZnO modified ZrO2 composite,CCA|ZnO supported on ZrO2 (m: n) modified catalyst,zinc oxide,None,total alcohol
2,10.1016/j.apcatb.2021.120739,None,CCA|ZnO|CCA|ZnO supported on ZrO2 catalyst,oxygen atom,None,alcohol
3,10.1016/j.apcatb.2021.120739,None,CCA|ZnO supported on ZrO2 (4:1) catalyst,aluminium atom,None,None
4,10.1016/j.apcatb.2021.120739,None,dioxozirconium,Lobenzarit disodium,None,None
5,10.1016/j.apcatb.2021.120739,None,None,aluminum;cobalt(2+);copper(1+),None,None
6,10.1016/j.apcatb.2021.120739,None,None,copper atom,None,None
7,10.1016/j.apcatb.2021.120739,None,None,cobalt atom,None,None
8,10.1016/j.apcatb.2021.120739,None,None,dioxozirconium,None,None
0,10.1016/j.ijhydene.2023.12.292,CuZnAl catalyst,None,copper atom,higher alcohol,higher alcohol
1,10.1016/j.ijhydene.2023.12.292,None,None,aluminum;zinc;copper(1+),None,None
2,10.1016/j.ijhydene.2023.12.292,None,None,copper(II) oxide,None,None
3,10.1016/j.ijhydene.2023.12.292,None,None,aluminium atom,None,None
0,10.1021/acscatal.3c00363,None,None,(FexCoy)2C alloy carbide,None,oxygenate
1,10.1021/acscatal.3c00363,None,None,cobalt atom,None,None
2,10.1021/acscatal.3c00363,None,None,carbide,None,None
3,10.1021/acscatal.3c00363,None,None,iron atom,None,None
0,10.1021/ie502425d,5Pd supported on ZnO supported on Al2O3),zinc oxide,iron atom,dimethyl ether,hydrocarbon
1,10.1021/ie502425d,HAS catalyst,palladium,zinc oxide,methanol,methanol
2,10.1021/ie502425d,5Pd supported on ZnO supported on Al2O3,5Pd supported on ZnO supported on Al2O3,palladium,None,C5+ hydrocarbon
3,10.1021/ie502425d,0.5Pd supported on FeCoCu,5Pd supported on ZnO supported on Al2O3),aluminium oxide,None,None
4,10.1021/ie502425d,None,cobalt;copper;iron,hexadehydroastechrome,None,None
5,10.1021/ie502425d,None,0.5Pd supported on FeCoCu,copper atom,None,None
6,10.1021/ie502425d,None,0.5Pd supported on FeCoCu (HAS) catalyst,cobalt atom,None,None
7,10.1021/ie502425d,None,None,HZSM-5,None,None
0,10.1016/j.fuel.2023.127500,hcp-Co supported on Co2C catalyst,None,cobalt atom,higher alcohol,higher alcohol
1,10.1016/j.fuel.2023.127500,None,None,fcc-Co,acetylene,None
2,10.1016/j.fuel.2023.127500,None,None,hcp-Co,None,None
3,10.1016/j.fuel.2023.127500,None,None,Co2C,None,None
0,10.1016/j.fuproc.2022.107600,electronically modified ZnO catalyst,None,zinc oxide,higher alcohol,higher alcohol
1,10.1016/j.fuproc.2022.107600,None,None,ZnO doping with 4 mol% Cu,methanol,methanol
2,10.1016/j.fuproc.2022.107600,None,None,copper atom,None,None
0,10.1021/acs.iecr.3c02379,Co np,LaAl1-xCoxO3 (x = 0.2-0.5) were supported on ZrO2,lanthanum atom,higher alcohol,higher alcohol
1,10.1021/acs.iecr.3c02379,LaAl1-xCoxO3 (x = 0.2-0.5) were supported on ZrO2,Co-LaAlO3 supported on ZrO2,zirconium atom,None,None
2,10.1021/acs.iecr.3c02379,Co-LaAlO3 supported on ZrO2,dioxozirconium,LaAl1-xCoxO3,None,None
3,10.1021/acs.iecr.3c02379,None,None,aluminum;lanthanum(3+);oxygen(2-),None,None
4,10.1021/acs.iecr.3c02379,None,None,oxygen atom,None,None
5,10.1021/acs.iecr.3c02379,None,None,Coδ+/Co0,None,None
6,10.1021/acs.iecr.3c02379,None,None,aluminium atom,None,None
7,10.1021/acs.iecr.3c02379,None,None,(Z)-dehydrocyclopeptine,None,None
8,10.1021/acs.iecr.3c02379,None,None,cobalt atom,None,None
9,10.1021/acs.iecr.3c02379,None,None,dioxozirconium,None,None
0,10.1016/j.checat.2024.101010,Fe3O4-Fe5C2,None,iron atom,higher alcohol,higher alcohol
1,10.1016/j.checat.2024.101010,Fe catalyst,None,Fe5C2,None,None
2,10.1016/j.checat.2024.101010,None,None,ferrosoferric oxide,None,None
3,10.1016/j.checat.2024.101010,None,None,Iron with 10 mol% ZrO2,None,None
4,10.1016/j.checat.2024.101010,None,None,Promoted monometallic iron,None,None
5,10.1016/j.checat.2024.101010,None,None,dioxozirconium,None,None
0,10.1016/j.apsusc.2021.151846,La0.9K0.1CoxFe1-xO3 supported on ZrO2,La0.9K0.1CoxFe1-xO3 supported on ZrO2,LaFeO3-ZrO2,higher alcohol,higher alcohol
1,10.1016/j.apsusc.2021.151846,oxygen vacancy boosted Co-Co2C catalyst,dioxozirconium,lanthanum atom,None,alcohol
2,10.1016/j.apsusc.2021.151846,Co-Co2C catalyst,None,zirconium atom,None,None
3,10.1016/j.apsusc.2021.151846,oxygen vacancy promoted Co-Co2C catalyst,None,iron atom,None,None
4,10.1016/j.apsusc.2021.151846,None,None,Co2C,None,None
5,10.1016/j.apsusc.2021.151846,None,None,Co-Co2C,None,None
6,10.1016/j.apsusc.2021.151846,None,None,oxygen atom,None,None
7,10.1016/j.apsusc.2021.151846,None,None,K2O-La2O3,None,None
8,10.1016/j.apsusc.2021.151846,None,None,potassium atom,None,None
9,10.1016/j.apsusc.2021.151846,None,None,La0.9K0.1CoxFe1-xO3,None,None

### Export

In [ ]:
output_path='./output/output_BASCAT_2024-10-02.xlsx' #define the output path

df_all.to_excel(output_path)

## END

In [ ]:
sup_list=get_support(sup=None,doi=doi)
_,sup_all=get_synonyms(sup_list)
print('all queried synonyms of support:')
print(list(sup_all.values()))

In [4]:
onto_pub_list

49

In [ ]:
sup_list=get_support(sup=None,doi=doi,only_doi= False)
sup_cat=[]
for i in range(len(sup_list)):
    sup_cat.append([sup_list[i][1],sup_list[i][2]])
print(sup_cat)

Perform a search in scopus using collected information from ontology\
Queries have following structure: 'TITLE-ABS-KEY("reaction"AND"catalyst"AND"support material"AND"reactant"AND"product")' in all possible combinations

In [6]:
import pybliometrics
pybliometrics.scopus.init()

doi=None
df_all=scopus_seach_process(doi, onto_pub_list)

processing publication #1
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"carbon monoxide"AND"higher alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"carbon monoxide"AND"thermocatalytic ethanol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"carbon monoxide"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CO"AND"EtOH")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CO"AND"thermocatalytic ethanol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"EtOH")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"alcohol etilico"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"alcohol etilico"AND"CH3OH")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"alcohol etilico"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"EtOH"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"EtOH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"EtOH"AND"Methyl alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"EtOH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"thermo-catalytic CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"thermo-catalytic CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"thermo-catalytic CO"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"thermo-catalytic CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"thermo-catalytic CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"thermo-catalytic CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"thermo-catalytic CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"thermo-catalytic CO"AND"Methyl alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"thermo-catalytic CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"thermo-catalytic CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"thermo-catalytic CO"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"higher alcohol"AND"methane")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"higher alcohol"AND"hydrocarbon")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"higher alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"Methyl alcohol"AND"methane")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"higher alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"Methyl alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"Methyl alcohol"AND"thermocatalytic ethanol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"Methyl alcohol"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CH3OH"AND"EtOH")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CH3OH"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ternary-alloyed CoCu2Ga nanoparticle supported on silica"AND"CH3OH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo intermetallic"AND"CH3OH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"thermocatalytic ethanol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"SiO2"AND"CH3OH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"SiO2"AND"CH3OH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CH3OH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CH3OH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"SiO2"AND"CH3OH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"SiO2"AND"CH3OH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"Kieselsaeureanhydrid"AND"CH3OH"AND"thermocatalytic ethanol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CoCu2Ga"AND"SiO2"AND"CH3OH"AND"thermocatalytic ethanol")
processing publication #2
processing publication #3
processing publication #4
processing publication #5
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"carbon monoxide"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"carbon monoxide"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"carbon monoxide"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"carbon monoxide"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"carbon monoxide"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"carbon monoxide"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"CO"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"CO"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"CO"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"CO"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"CO"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"CO"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"alcohol etilico"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"alcohol etilico"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"alcohol etilico"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"alcohol etilico"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"alcohol etilico"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"alcohol etilico"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"alcohol etilico"AND"higher alcohol")

Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"EtOH"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"EtOH"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"EtOH"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"EtOH"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"EtOH"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"EtOH"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"higher alcohol"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"higher alcohol"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"higher alcohol"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"higher alcohol"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"higher alcohol"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"higher alcohol"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rhodium catalyst"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"carbon monoxide"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"carbon monoxide"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"carbon monoxide"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"carbon monoxide"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"carbon monoxide"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"carbon monoxide"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"CO"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"CO"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"CO"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"CO"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"CO"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"CO"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"CO"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"alcohol etilico"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"alcohol etilico"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"alcohol etilico"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"alcohol etilico"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"alcohol etilico"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"alcohol etilico"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"EtOH"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"EtOH"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"EtOH"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"EtOH"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"EtOH"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"EtOH"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"higher alcohol"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"higher alcohol"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"higher alcohol"AND"methoxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"higher alcohol"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"higher alcohol"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"higher alcohol"AND"CH2OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rhodium catalyst"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"higher alcohol"AND"higher alcohol")
processing publication #6
processing publication #7
processing publication #8
processing publication #9
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"higher alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"carbon monoxide"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"carbon monoxide"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"carbon monoxide"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"carbon monoxide"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"carbon monoxide"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"carbon monoxide"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"carbon monoxide"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"carbon monoxide"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"carbon monoxide"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"CO"AND"hydrocarbon")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"direct CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"direct CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"direct CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"direct CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"direct CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"direct CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"direct CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"direct CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"direct CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"direct CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"direct CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"direct CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"direct CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"direct CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"direct CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"direct CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"direct CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"direct CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"direct CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"direct CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"direct CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"direct CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"direct CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"direct CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"direct CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"direct CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"direct CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"direct CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"direct CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"direct CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"direct CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"direct CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"direct CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"direct CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"direct CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"direct CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"direct CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"direct CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"direct CO"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"direct CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"direct CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"direct CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"direct CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"direct CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"direct CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"direct CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"direct CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"direct CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"direct CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"direct CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"direct CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"direct CO"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"higher alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"higher alcohol"AND"hydrocarbon")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe supported on SiO2 catalyst"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"SiO2"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"SiO2"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"SiO2"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"SiO2"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;iron"AND"SiO2"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"Kieselsaeureanhydrid"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuFe"AND"SiO2"AND"higher alcohol"AND"total alcohol")
processing publication #10
processing publication #11
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZrO2-free counterpart"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co1Fe4 supported on ZrO2-10"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co1Fe4@ZrO2-10"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co-Fe m-FTS"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu:Co = 1:4, 5 mol% ZrO2"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu:Co = 1:4, 5 mol% ZrO2"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"5-10 mol% ZrO2"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"5-10 mol% ZrO2"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND"ZrO2-5"AND"carbon monoxide"AND" ")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;iron"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;iron"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co1Fe4"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co1Fe4"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Co4"AND"dioxozirconium"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Co4"AND"ZrO2-5"AND"carbon monoxide"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZrO2-free counterpart"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co1Fe4 supported on ZrO2-10"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co1Fe4@ZrO2-10"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co-Fe m-FTS"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu:Co = 1:4, 5 mol% ZrO2"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu:Co = 1:4, 5 mol% ZrO2"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"5-10 mol% ZrO2"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"5-10 mol% ZrO2"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;copper"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;iron"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt;iron"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co1Fe4"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co1Fe4"AND"ZrO2-5"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Co4"AND"dioxozirconium"AND"CO"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Co4"AND"ZrO2-5"AND"CO"AND" ")
processing publication #12
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"carbon monoxide"AND"carbon dioxide")

Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"alcohol etilico"AND"EtOH")

Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"dimethyl ether"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"CH3-O-CH3"AND"carbon dioxide")

Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx supported on γ-Al2O3"AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx/γ-Al2O3"AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"copper atom"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"oxygen atom"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"O"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"aluminium atom"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Al"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"γ-Al2O3"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"Cu1Zn2AlOx"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("carbonylation"AND"CuZnAlOx"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"carbon monoxide"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"carbon monoxide"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"CO"AND"EtOH")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"CO"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"CO"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"EtOH"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"dimethyl ether"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"dimethyl ether"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"dimethyl ether"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"dimethyl ether"AND"CO2")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"dimethyl ether"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"CH3-O-CH3"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"CH3-O-CH3"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"CH3-O-CH3"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx supported on γ-Al2O3"AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx/γ-Al2O3"AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"γ-Al2O3"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu1Zn2AlOx"AND" "AND"CH3-O-CH3"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAlOx"AND" "AND"CH3-O-CH3"AND"CO2")
processing publication #13
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"carbon monoxide"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"carbon monoxide"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"carbon monoxide"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"carbon monoxide"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"carbon monoxide"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"carbon monoxide"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"CO"AND"higher alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"CO"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"CO"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CO"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CO"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"CO"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"CO"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"higher alcohol"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"higher alcohol"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"higher alcohol"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"higher alcohol"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"higher alcohol"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"higher alcohol"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"Methyl alcohol"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"Methyl alcohol"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"Methyl alcohol"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"Methyl alcohol"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"Methyl alcohol"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"Methyl alcohol"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CH3OH"AND"higher alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND"CH3OH"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND"CH3OH"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"CH3OH"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"CH3OH"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND"CH3OH"AND"C2-4OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND"CH3OH"AND"C2-4OH")
processing publication #14
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"carbon monoxide"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"carbon monoxide"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"carbon monoxide"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"carbon monoxide"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"carbon monoxide"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"carbon monoxide"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"carbon monoxide"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"carbon monoxide"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"carbon monoxide"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"carbon monoxide"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"carbon monoxide"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"carbon monoxide"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"carbon monoxide"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"carbon monoxide"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"carbon monoxide"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"carbon monoxide"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"carbon monoxide"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"carbon monoxide"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"carbon monoxide"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"carbon monoxide"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"CO"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"CO"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"CO"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"CO"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"CO"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"CO"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"CO"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"CO"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"CO"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"CO"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"CO"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"CO"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"CO"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"CO"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"CO"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"CO"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"CO"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"CO"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"CO"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"CO"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"CO"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"alcohol etilico"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"alcohol etilico"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"alcohol etilico"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"alcohol etilico"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"alcohol etilico"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"alcohol etilico"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"alcohol etilico"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"alcohol etilico"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"alcohol etilico"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"alcohol etilico"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"alcohol etilico"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"alcohol etilico"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"alcohol etilico"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"alcohol etilico"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"alcohol etilico"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"alcohol etilico"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"alcohol etilico"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"alcohol etilico"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"alcohol etilico"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"alcohol etilico"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"EtOH"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"EtOH"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"EtOH"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"EtOH"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"EtOH"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"EtOH"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"EtOH"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"EtOH"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"EtOH"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"EtOH"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"EtOH"AND"naramycin")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on TiO2 catalyst"AND"EtOH"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh supported on the pure phase anatase or rutile TiO2"AND"EtOH"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"titanium dioxide"AND"EtOH"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"TiO2"AND"EtOH"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"titanium dioxide"AND"EtOH"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"TiO2"AND"EtOH"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"rhodium atom"AND"EtOH"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"titanium dioxide"AND"Rh"AND"EtOH"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"rhodium atom"AND"EtOH"AND"CHx")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TiO2"AND"Rh"AND"EtOH"AND"CHx")
processing publication #15
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"CO"AND"EtOH")

Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH-aw"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"ultrathin CuCoAl nanosheet"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"cobalt atom"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Co"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"copper atom"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"Cu"AND" "AND"higher alcohol"AND"higher alcohol")

Downloading results for query TITLE-ABS-KEY("hydrodeoxygenation"AND"CuCo-LDH"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"higher alcohol"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH-aw"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ultrathin CuCoAl nanosheet"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCo-LDH"AND" "AND"higher alcohol"AND"higher alcohol")
processing publication #16
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe catalyst"AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe"AND" "AND"carbon monoxide"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe catalyst"AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe"AND" "AND"carbon monoxide"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe catalyst"AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe catalyst"AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe"AND" "AND"CO"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe catalyst"AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe"AND" "AND"CO"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe catalyst"AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe catalyst"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe catalyst"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe"AND" "AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe catalyst"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CaFe"AND" "AND"higher alcohol"AND"oxygenate")
processing publication #17
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"carbon monoxide"AND"Aethan")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CO"AND"Methyl alcohol")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"methane")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"alcohol etilico"AND"CH3-CH3")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"EtOH"AND" ")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"ACETALDEHYDE")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"CH3OH")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"CH4")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"Aethan")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"Methyl alcohol"AND"EtOH")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"ACETALDEHYDE")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CH3OH"AND"oxygenate")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe/Mo6S8"AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"ruthenium atom"AND" "AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Ru"AND" "AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Threoninyl"AND" "AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"TM"AND" "AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Mo6S8"AND" "AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"Aethan")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"carbon monoxide"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CO"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CO"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CO"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CO"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CO"AND"Methyl alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CO"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CO"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CO"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CO"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CO"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CO"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CO"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"methane")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"CH3-CH3")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"alcohol etilico"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"EtOH"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"EtOH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"EtOH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"EtOH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"EtOH"AND"ACETALDEHYDE")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"EtOH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"CH3OH")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"hydridooxidocarbon"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"HCO(.)"AND"methane")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"HCO(.)"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"HCO(.)"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"HCO(.)"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"HCO(.)"AND"CH3-CH3")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"HCO(.)"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"HCO(.)"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"HCO(.)"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"HCO(.)"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"Methyl alcohol"AND"EtOH")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"Methyl alcohol"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"Acetaldehyde")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"Methyl alcohol"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CH3OH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CH3OH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CH3OH"AND" ")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CH3OH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CH3OH"AND"CH3-CH3")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CH3OH"AND"Aethan")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CH3OH"AND"Acetaldehyde")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 (TM = Fe, Ru) catalysts"AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe supported on Mo6S8"AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe/Mo6S8"AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM supported on Mo6S8 catalyst"AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ruthenium atom"AND" "AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ru"AND" "AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Threoninyl"AND" "AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"TM"AND" "AND"CH3OH"AND"ACETALDEHYDE")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mo6S8"AND" "AND"CH3OH"AND"ACETALDEHYDE")
processing publication #18
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"methane")

Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"EtOH")

Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")

Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"methane")

Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")

Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"EtOH"AND"oxygenate")

Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"methane")

Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")

Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")

Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Co"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"C"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("water-gas shift reaction"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"CH4")

Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")

Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")

Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"CH4")

Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND" ")

Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")

Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"EtOH"AND"oxygenate")

Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"CH4")

Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")

Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"alcohol")

Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Co"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"C"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")

Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("catalytic decomposition"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"alcohol etilico"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"EtOH"AND"methane")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"EtOH"AND"higher alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"EtOH"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"82Ni-8Cu supported on Al2O3 catalyst"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"catalyst supported on Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium oxide"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al2O3"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon-coated alumina"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"CNF-82Ni-8Cu/Al2O3"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"aluminium oxide"AND"higher alcohol"AND"oxygenate")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"fabric-activated carbon"AND"Al2O3"AND"higher alcohol"AND"oxygenate")
processing publication #19
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"2.0Rh5.0Ce-ZrO2 catalyst"AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cerio"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ce"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh5.0Ce-ZrO2"AND" "AND"alcohol etilico"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"2.0Rh5.0Ce-ZrO2 catalyst"AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cerio"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ce"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh5.0Ce-ZrO2"AND" "AND"alcohol etilico"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"2.0Rh5.0Ce-ZrO2 catalyst"AND"alcohol etilico"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cerio"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ce"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh5.0Ce-ZrO2"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"2.0Rh5.0Ce-ZrO2 catalyst"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cerio"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ce"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh5.0Ce-ZrO2"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"2.0Rh5.0Ce-ZrO2 catalyst"AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cerio"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ce"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh5.0Ce-ZrO2"AND" "AND"alcohol etilico"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"2.0Rh5.0Ce-ZrO2 catalyst"AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cerio"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ce"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh5.0Ce-ZrO2"AND" "AND"alcohol etilico"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"2.0Rh5.0Ce-ZrO2 catalyst"AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cerio"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ce"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh5.0Ce-ZrO2"AND" "AND"EtOH"AND"methane")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"2.0Rh5.0Ce-ZrO2 catalyst"AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cerio"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ce"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh5.0Ce-ZrO2"AND" "AND"EtOH"AND"CH4")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"2.0Rh5.0Ce-ZrO2 catalyst"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cerio"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ce"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh5.0Ce-ZrO2"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"2.0Rh5.0Ce-ZrO2 catalyst"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cerio"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ce"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh5.0Ce-ZrO2"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"2.0Rh5.0Ce-ZrO2 catalyst"AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cerio"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ce"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh5.0Ce-ZrO2"AND" "AND"EtOH"AND"carbon dioxide")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"2.0Rh5.0Ce-ZrO2 catalyst"AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"rhodium atom"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cerio"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ce"AND" "AND"EtOH"AND"CO2")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh5.0Ce-ZrO2"AND" "AND"EtOH"AND"CO2")
processing publication #20
processing publication #21
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh supported on P25 and different facet Cu2O nanocrystal"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh supported on P25 and 18 facet Cu2O nc"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh-based and Cu nc catalysts"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cuprous oxide"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu2O"AND" "AND"alcohol etilico"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"P25"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh supported on P25 and different facet Cu2O nanocrystal"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh supported on P25 and 18 facet Cu2O nc"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh-based and Cu nc catalysts"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cuprous oxide"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu2O"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"P25"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh supported on P25 and different facet Cu2O nanocrystal"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh supported on P25 and 18 facet Cu2O nc"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh-based and Cu nc catalysts"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cuprous oxide"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu2O"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"P25"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh supported on P25 and different facet Cu2O nanocrystal"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh supported on P25 and 18 facet Cu2O nc"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Rh-based and Cu nc catalysts"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cuprous oxide"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu2O"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"P25"AND" "AND"EtOH"AND" ")
processing publication #22
processing publication #23
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt atom"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt atom"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Co"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Co"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"oxygen atom"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"oxygen atom"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"O"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"O"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"zirconium atom"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"zirconium atom"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Zr"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Zr"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt;rhodium"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt;rhodium"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"RhCo"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"RhCo"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt atom"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt atom"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Co"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Co"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"oxygen atom"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"oxygen atom"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"O"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"O"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"zirconium atom"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"zirconium atom"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Zr"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Zr"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt;rhodium"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt;rhodium"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"RhCo"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"RhCo"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt atom"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt atom"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Co"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Co"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"oxygen atom"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("dissociation"AND"oxygen atom"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"O"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"O"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"zirconium atom"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"zirconium atom"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Zr"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Zr"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt;rhodium"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt;rhodium"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"RhCo"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"RhCo"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"rhodium atom"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Rh"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt atom"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt atom"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Co"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Co"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"oxygen atom"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"oxygen atom"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"O"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"O"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"zirconium atom"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"zirconium atom"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Zr"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Zr"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt;rhodium"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt;rhodium"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"RhCo"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"RhCo"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"oxygen atom"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"oxygen atom"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"O"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"O"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"zirconium atom"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"zirconium atom"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Zr"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Zr"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt;rhodium"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt;rhodium"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"RhCo"AND"dioxozirconium"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"RhCo"AND"ZrO2-5"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"oxygen atom"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"oxygen atom"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"O"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"O"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"zirconium atom"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"zirconium atom"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Zr"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Zr"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt;rhodium"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt;rhodium"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"RhCo"AND"dioxozirconium"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"RhCo"AND"ZrO2-5"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")

Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"oxygen atom"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"oxygen atom"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"O"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"O"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"zirconium atom"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"zirconium atom"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Zr"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Zr"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt;rhodium"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt;rhodium"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"RhCo"AND"dioxozirconium"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"RhCo"AND"ZrO2-5"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"rhodium atom"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Rh"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"oxygen atom"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"oxygen atom"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"O"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"O"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"zirconium atom"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"zirconium atom"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Zr"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Zr"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt;rhodium"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt;rhodium"AND"ZrO2-5"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"RhCo"AND"dioxozirconium"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("insertion"AND"RhCo"AND"ZrO2-5"AND"EtOH"AND" ")
processing publication #24
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"alcohol etilico"AND"Methyl alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"alcohol etilico"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"alcohol etilico"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"EtOH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"EtOH"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"EtOH"AND"CH3OH")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"hydridooxidocarbon"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"hydridooxidocarbon"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"hydridooxidocarbon"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"hydridooxidocarbon"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"HCO(.)"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"HCO(.)"AND"EtOH")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"HCO(.)"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"HCO(.)"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"HCO(.)"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"Methyl alcohol"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"Methyl alcohol"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"Methyl alcohol"AND"Methyl alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"CH3OH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"CH3OH"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu supported on ZnO catalyst"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001) catalyst"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4 supported on ZnO(0001)-5%Ov"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu4/ZnO(0001)-5%Ov"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"Zinkoxid"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZnO"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"Zinkoxid"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZnO"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"Zinkoxid"AND"CH3OH"AND" ")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"1-(4-cyanophenyl)-N-(3-fluorophenyl)-3-(4-methylsulfonylphenyl)pyrazole-4-carboxamide"AND"ZnO"AND"CH3OH"AND" ")
processing publication #25
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl catalyst"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl supported on S-1"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl@S-1"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZn supported on S-1"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZn@S-1"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CZA supported on S-1"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CZA@S-1"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CZA supported on S-1 catalyst"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnAl supported on S-1"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnAl@S-1"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuAl supported on S-1"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuAl@S-1"AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;zinc;copper(1"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;zinc"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZn"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"LSM-1306"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;copper"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuAl"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnAl"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"S-1"AND" "AND"alcohol etilico"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl catalyst"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl supported on S-1"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl@S-1"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZn supported on S-1"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZn@S-1"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CZA supported on S-1"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CZA@S-1"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CZA supported on S-1 catalyst"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnAl supported on S-1"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnAl@S-1"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuAl supported on S-1"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuAl@S-1"AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;zinc;copper(1"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;zinc"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZn"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"LSM-1306"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;copper"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuAl"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnAl"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"S-1"AND" "AND"alcohol etilico"AND"EtOH")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl catalyst"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl supported on S-1"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl@S-1"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZn supported on S-1"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZn@S-1"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CZA supported on S-1"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CZA@S-1"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CZA supported on S-1 catalyst"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnAl supported on S-1"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnAl@S-1"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuAl supported on S-1"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuAl@S-1"AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;zinc;copper(1"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;zinc"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZn"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"LSM-1306"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;copper"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuAl"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnAl"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"S-1"AND" "AND"EtOH"AND"alcohol etilico")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl catalyst"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl supported on S-1"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl@S-1"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZn supported on S-1"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZn@S-1"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CZA supported on S-1"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CZA@S-1"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CZA supported on S-1 catalyst"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnAl supported on S-1"AND"EtOH"AND" ")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnAl@S-1"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuAl supported on S-1"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuAl@S-1"AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;zinc;copper(1"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;zinc"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZn"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"LSM-1306"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;copper"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuAl"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnAl"AND" "AND"EtOH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"S-1"AND" "AND"EtOH"AND" ")
processing publication #26
processing publication #27
processing publication #28
processing publication #29
processing publication #30
processing publication #31
processing publication #32
Downloading results for query TITLE-ABS-KEY("roh"AND"Mg-modified mesoporous silica (Mg-MS-x)"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"KNiMoS catalysts"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"KNiMoS supported on Mg-MS-20"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"KNiMoS/Mg-MS-20"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"Kieselsaeureanhydrid"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"SiO2"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"MoS2"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"molybdenum disulphide"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"ordered mesoporous silica confined KNiMoS"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"KNiMoS"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"potassium atom"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"K"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"nickel atom"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"Ni"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"Mg-MS-x"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("roh"AND"Mg-MS-20"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mg-modified mesoporous silica (Mg-MS-x)"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"KNiMoS catalysts"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"KNiMoS supported on Mg-MS-20"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"KNiMoS/Mg-MS-20"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Kieselsaeureanhydrid"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"SiO2"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"MoS2"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum disulphide"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ordered mesoporous silica confined KNiMoS"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"KNiMoS"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"potassium atom"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"K"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"nickel atom"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Ni"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mg-MS-x"AND" "AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Mg-MS-20"AND" "AND" "AND"alcohol")
processing publication #33
Downloading results for query TITLE-ABS-KEY("insertion"AND"carbon-coated ordered mesoporous silica (OMS) supported cobalt catalyst"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"carbon-coated amorphous SiO2 supported sample"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"carbon-silica composite support"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co supported on 10C supported on OMS"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co/10C/OMS"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co supported on xC supported on OMS"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co/xC/OMS"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co-Co2C catalyst"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Kieselsaeureanhydrid"AND"carbon atom"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Kieselsaeureanhydrid"AND"C"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"SiO2"AND"carbon atom"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"SiO2"AND"C"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Kieselsaeureanhydrid"AND"(1-methylcyclobutyl) N-[(1S,4R,6S,7Z,14S,18R)-18-(7-methoxy-3-methylquinoxalin-2-yl)oxy-4-[(1-methylcyclopropyl)sulfonylcarbamoyl]-2,15-dioxo-3,16-diazatricyclo[14.3.0.04,6]nonadec-7-en-14-yl]carbamate"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Kieselsaeureanhydrid"AND"OMS"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"SiO2"AND"(1-methylcyclobutyl) N-[(1S,4R,6S,7Z,14S,18R)-18-(7-methoxy-3-methylquinoxalin-2-yl)oxy-4-[(1-methylcyclopropyl)sulfonylcarbamoyl]-2,15-dioxo-3,16-diazatricyclo[14.3.0.04,6]nonadec-7-en-14-yl]carbamate"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"SiO2"AND"OMS"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Kieselsaeureanhydrid"AND"sodium;4-(Z)-4-(ethylamino)-3-methylphenyl-(4-ethylimino-3-methylcyclohexa-2,5-dien-1-ylidene)methyl-3-sulfobenzenesulfonate"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"SiO2"AND"sodium;4-(Z)-4-(ethylamino)-3-methylphenyl-(4-ethylimino-3-methylcyclohexa-2,5-dien-1-ylidene)methyl-3-sulfobenzenesulfonate"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"Kieselsaeureanhydrid"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"SiO2"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"Kieselsaeureanhydrid"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"SiO2"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"carbon atom"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"C"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"carbon atom"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"C"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"(1-methylcyclobutyl) N-[(1S,4R,6S,7Z,14S,18R)-18-(7-methoxy-3-methylquinoxalin-2-yl)oxy-4-[(1-methylcyclopropyl)sulfonylcarbamoyl]-2,15-dioxo-3,16-diazatricyclo[14.3.0.04,6]nonadec-7-en-14-yl]carbamate"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"OMS"AND" "AND"alcohol")

Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"(1-methylcyclobutyl) N-[(1S,4R,6S,7Z,14S,18R)-18-(7-methoxy-3-methylquinoxalin-2-yl)oxy-4-[(1-methylcyclopropyl)sulfonylcarbamoyl]-2,15-dioxo-3,16-diazatricyclo[14.3.0.04,6]nonadec-7-en-14-yl]carbamate"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"OMS"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"cobalt atom"AND"sodium;4-(Z)-4-(ethylamino)-3-methylphenyl-(4-ethylimino-3-methylcyclohexa-2,5-dien-1-ylidene)methyl-3-sulfobenzenesulfonate"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co"AND"sodium;4-(Z)-4-(ethylamino)-3-methylphenyl-(4-ethylimino-3-methylcyclohexa-2,5-dien-1-ylidene)methyl-3-sulfobenzenesulfonate"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co-Co2C"AND"Kieselsaeureanhydrid"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co-Co2C"AND"SiO2"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co-Co2C"AND"carbon atom"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co-Co2C"AND"C"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co-Co2C"AND"(1-methylcyclobutyl) N-[(1S,4R,6S,7Z,14S,18R)-18-(7-methoxy-3-methylquinoxalin-2-yl)oxy-4-[(1-methylcyclopropyl)sulfonylcarbamoyl]-2,15-dioxo-3,16-diazatricyclo[14.3.0.04,6]nonadec-7-en-14-yl]carbamate"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co-Co2C"AND"OMS"AND" "AND"alcohol")
Downloading results for query TITLE-ABS-KEY("insertion"AND"Co-Co2C"AND"sodium;4-(Z)-4-(ethylamino)-3-methylphenyl-(4-ethylimino-3-methylcyclohexa-2,5-dien-1-ylidene)methyl-3-sulfobenzenesulfonate"AND" "AND"alcohol")
processing publication #34
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbide catalyst"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"open mesoporous lignin carbon"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum carbide"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"porous nano molybdenum carbide"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbide"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbide catalyst"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbon atom"AND" "AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"C"AND" "AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"open mesoporous lignin carbon"AND" "AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"molybdenum carbide"AND" "AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"porous nano molybdenum carbide"AND" "AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"carbide"AND" "AND"higher alcohol"AND"alcohol")
processing publication #35
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CuZn catalyst"AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CZ-0.80 catalyst"AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"iron atom"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Fe"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"cobalt atom"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Co"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"copper atom"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"Cu"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"electron-rich Cu"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"copper;zinc"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CuZn"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("dissociation"AND"CZ-0.80"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZn catalyst"AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CZ-0.80 catalyst"AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"iron atom"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Fe"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"electron-rich Cu"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper;zinc"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZn"AND" "AND"coal"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CZ-0.80"AND" "AND"coal"AND"alcohol")
processing publication #36
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnO modified ZrO2 composite"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CCA|ZnO|CCA|ZnO supported on ZrO2 catalyst"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zinkoxid"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zinkoxid"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnO"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnO"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Lobenzarit disodium"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Lobenzarit disodium"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CCA"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CCA"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;cobalt(2+);copper(1"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;cobalt(2+);copper(1"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCoAl"AND"dioxozirconium"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCoAl"AND"ZrO2-5"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnO modified ZrO2 composite"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CCA|ZnO|CCA|ZnO supported on ZrO2 catalyst"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zinkoxid"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zinkoxid"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnO"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnO"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Lobenzarit disodium"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Lobenzarit disodium"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CCA"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CCA"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;cobalt(2+);copper(1"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;cobalt(2+);copper(1"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCoAl"AND"dioxozirconium"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCoAl"AND"ZrO2-5"AND"higher alcohol"AND"alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnO modified ZrO2 composite"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CCA|ZnO|CCA|ZnO supported on ZrO2 catalyst"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zinkoxid"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zinkoxid"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnO"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"ZnO"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cobalt atom"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Co"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"copper atom"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Cu"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"oxygen atom"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")

Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"O"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"zirconium atom"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Zr"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Lobenzarit disodium"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Lobenzarit disodium"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CCA"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CCA"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;cobalt(2+);copper(1"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;cobalt(2+);copper(1"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCoAl"AND"dioxozirconium"AND"higher alcohol"AND"total alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuCoAl"AND"ZrO2-5"AND"higher alcohol"AND"total alcohol")
processing publication #37
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl catalyst"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"cupric oxide"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuO"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminum;zinc;copper(1"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"CuZnAl"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"aluminium atom"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrogenation"AND"Al"AND" "AND"higher alcohol"AND"higher alcohol")
processing publication #38
no queries for publication
processing publication #39
processing publication #40
processing publication #41
Downloading results for query TITLE-ABS-KEY("carbonization"AND"hcp-Co supported on Co2C catalyst"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("carbonization"AND"cobalt atom"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("carbonization"AND"Co"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("carbonization"AND"fcc-Co"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("carbonization"AND"hcp-Co"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("carbonization"AND"Co2C"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("carbonization"AND"hcp-Co supported on Co2C catalyst"AND"acetylene"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("carbonization"AND"cobalt atom"AND" "AND"acetylene"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("carbonization"AND"Co"AND" "AND"acetylene"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("carbonization"AND"fcc-Co"AND" "AND"acetylene"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("carbonization"AND"hcp-Co"AND" "AND"acetylene"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("carbonization"AND"Co2C"AND" "AND"acetylene"AND"higher alcohol")
processing publication #42
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"electronically modified ZnO catalyst"AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Zinkoxid"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO doping with 4 mol% Cu"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"copper atom"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Cu"AND" "AND"higher alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"electronically modified ZnO catalyst"AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Zinkoxid"AND" "AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO"AND" "AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO doping with 4 mol% Cu"AND" "AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"copper atom"AND" "AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Cu"AND" "AND"higher alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"electronically modified ZnO catalyst"AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Zinkoxid"AND" "AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO"AND" "AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO doping with 4 mol% Cu"AND" "AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"copper atom"AND" "AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Cu"AND" "AND"higher alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"electronically modified ZnO catalyst"AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Zinkoxid"AND" "AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO"AND" "AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO doping with 4 mol% Cu"AND" "AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"copper atom"AND" "AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Cu"AND" "AND"Methyl alcohol"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"electronically modified ZnO catalyst"AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Zinkoxid"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO doping with 4 mol% Cu"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"copper atom"AND" "AND"Methyl alcohol"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Cu"AND" "AND"Methyl alcohol"AND"Methyl alcohol")

Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"electronically modified ZnO catalyst"AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Zinkoxid"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO doping with 4 mol% Cu"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"copper atom"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Cu"AND" "AND"Methyl alcohol"AND"CH3OH")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"electronically modified ZnO catalyst"AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Zinkoxid"AND" "AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO"AND" "AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO doping with 4 mol% Cu"AND" "AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"copper atom"AND" "AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Cu"AND" "AND"CH3OH"AND"higher alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"electronically modified ZnO catalyst"AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Zinkoxid"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO doping with 4 mol% Cu"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"copper atom"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Cu"AND" "AND"CH3OH"AND"Methyl alcohol")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"electronically modified ZnO catalyst"AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Zinkoxid"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"ZnO doping with 4 mol% Cu"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"copper atom"AND" "AND"CH3OH"AND" ")
Downloading results for query TITLE-ABS-KEY("hydrolysis"AND"Cu"AND" "AND"CH3OH"AND" ")
processing publication #43
processing publication #44
processing publication #45
processing publication #46
processing publication #47
processing publication #48
processing publication #49
no queries for publication

All distinct results are saved in sheet 'distinct_eid'.\
Filter found publication according to the start and end date\
If no filtering nessesary define `start_date` as follows:\
`get_synonyms = None`

In [11]:
start_date = '2023-01-01'
end_date = '2024-12-31' 

distinct_df, filtered_df, filtered_df_doi, filtered_df_doi_new = filter_date(start_date,end_date, df_all,onto_pub_list)

save from scopus quieried publication information in Excel

In [12]:
output_path='./output/output_bascat_2024-10-30_1yrs.xlsx' #define the output path

save_in_excel(output_path, df_all, distinct_df, filtered_df, filtered_df_doi, filtered_df_doi_new )