In [21]:
import pandas as pd
from queries import *
import pybliometrics

pybliometrics.scopus.init()

In [2]:
#load the ontology from "./ontologies/" and perform reasoning
onto_name= "afo_dataset-1-2024-03-05" #input name of the ontology

#perform reasoning, get dois from publications in the extended ontology
onto_pub_list,onto,df=reasoning_dois_onto(onto_name)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
 
display(df)

* Owlready2 * WARNING: DataProperty http://xmlns.com/foaf/0.1/name belongs to more than one entity types: [owl.AnnotationProperty, owl.DatatypeProperty]; I'm trying to fix it...
* Owlready2 * Running HermiT...
    java -Xmx2000M -cp C:\Users\smaxbehr\AppData\Local\anaconda3\envs\testenv\lib\site-packages\owlready2\hermit;C:\Users\smaxbehr\AppData\Local\anaconda3\envs\testenv\lib\site-packages\owlready2\hermit\HermiT.jar org.semanticweb.HermiT.cli.CommandLine -c -O -D -I file:///C:/Users/smaxbehr/AppData/Local/Temp/tmpln4_3mvv
* Owlready2 * HermiT took 88.17190623283386 seconds
* Owlready * Reparenting obo.RO_0002213: {owl.ObjectProperty, obo.RO_0002304, obo.RO_0002211} => {obo.RO_0002304, obo.RO_0002211}
* Owlready * Reparenting core.narrowMatch: {core.mappingRelation, owl.ObjectProperty, core.narrower} => {core.mappingRelation, core.narrower}
* Owlready * Reparenting core.relatedMatch: {core.mappingRelation, owl.ObjectProperty, owl.SymmetricProperty, core.related} => {core.related, core.mappingRelation}
* Owlready * Reparenting obo.RO_0002220: {owl.ObjectProperty, obo.RO_0002163} => {obo.RO_0002163}
* Owlready * Reparenting obo.RO_0002342: {owl.ObjectProperty, obo.RO_0002344} => {obo.RO_0002344}
* Owlready * Reparenting obo.RO_0002339: {owl.ObjectProperty, obo.RO_0002344} => {obo.RO_0002344}
* Owlready * Reparenting obo.RO_0002338: {owl.ObjectProperty, obo.RO_0002344} => {obo.RO_0002344}
* Owlready * Reparenting property.AFX_0000551: {owl.AsymmetricProperty, owl.ObjectProperty, owl.IrreflexiveProperty, obo.RO_0002351} => {obo.RO_0002351}
* Owlready * Reparenting property.AFX_0001048: {owl.ObjectProperty, obo.RO_0001015} => {obo.RO_0001015}
* Owlready * Reparenting property.AFX_0002703: {owl.ObjectProperty, obo.BFO_0000133} => {obo.BFO_0000133}
* Owlready * Reparenting obo.RO_0002463: {owl.ObjectProperty, obo.RO_0002461} => {obo.RO_0002461}
* Owlready * Reparenting obo.RO_0002462: {owl.ObjectProperty, obo.RO_0002461} => {obo.RO_0002461}
* Owlready * Reparenting property.AFX_0001179: {obo.RO_0002170, owl.ObjectProperty} => {obo.RO_0002170}
* Owlready * Reparenting property.AFX_0001178: {obo.RO_0002170, owl.ObjectProperty} => {obo.RO_0002170}
* Owlready * Reparenting obo.RO_0002304: {owl.ObjectProperty, obo.RO_0002411} => {obo.RO_0002411}
* Owlready * Reparenting obo.RO_0002305: {owl.ObjectProperty, obo.RO_0002411} => {obo.RO_0002411}
* Owlready * Reparenting obo.RO_0002515: {owl.ObjectProperty, obo.RO_0002527} => {obo.RO_0002527}
* Owlready * Reparenting obo.RO_0002529: {owl.ObjectProperty, obo.RO_0002527, owl.TransitiveProperty} => {obo.RO_0002527, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002528: {owl.ObjectProperty, obo.RO_0002527, owl.TransitiveProperty} => {obo.RO_0002527, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002428: {obo.RO_0002431, owl.ObjectProperty, obo.RO_0002263} => {obo.RO_0002431, obo.RO_0002263}
* Owlready * Reparenting property.AFX_0002735: {owl.ObjectProperty, property.AFX_0000353} => {property.AFX_0000353}
* Owlready * Reparenting property.AFX_0000974: {owl.ObjectProperty, property.AFX_0000972, owl.TransitiveProperty} => {property.AFX_0000972}
* Owlready * Reparenting property.AFX_0000546: {owl.ObjectProperty, property.AFX_0000395} => {property.AFX_0000395}
* Owlready * Reparenting obo.RO_0002327: {owl.ObjectProperty, obo.RO_0002215} => {obo.RO_0002215}
* Owlready * Reparenting property.AFX_0000365: {owl.ObjectProperty, property.AFX_0002793} => {property.AFX_0002793}
* Owlready * Reparenting property.AFX_0002832: {owl.ObjectProperty, property.AFX_0002793} => {property.AFX_0002793}
* Owlready * Reparenting obo.OBI_0000643: {owl.ObjectProperty, property.AFX_0002793, owl.TransitiveProperty} => {property.AFX_0002793}
* Owlready * Reparenting obo.RO_0002351: {owl.AsymmetricProperty, owl.ObjectProperty, property.AFX_0002793, owl.IrreflexiveProperty} => {owl.AsymmetricProperty, owl.IrreflexiveProperty, property.AFX_0002793}
* Owlready * Reparenting property.AFX_0002833: {owl.ObjectProperty, owl.TransitiveProperty, property.AFX_0002858} => {owl.TransitiveProperty, property.AFX_0002858}
* Owlready * Reparenting obo.BFO_0000185: {owl.ObjectProperty, owl.InverseFunctionalProperty, obo.BFO_0000067} => {owl.InverseFunctionalProperty, obo.BFO_0000067}
* Owlready * Reparenting obo.RO_0002531: {obo.RO_0002528, owl.ObjectProperty, obo.RO_0002515} => {obo.RO_0002528, obo.RO_0002515}
* Owlready * Reparenting obo.RO_0002530: {owl.ObjectProperty, obo.RO_0002515, obo.RO_0002529} => {obo.RO_0002515, obo.RO_0002529}
* Owlready * Reparenting obo.RO_0002429: {owl.ObjectProperty, obo.RO_0002428} => {obo.RO_0002428}
* Owlready * Reparenting obo.RO_0002430: {owl.ObjectProperty, obo.RO_0002428} => {obo.RO_0002428}
* Owlready * Reparenting obo.RO_0002212: {owl.ObjectProperty, obo.RO_0002305, obo.RO_0002211} => {obo.RO_0002305, obo.RO_0002211}
* Owlready * Reparenting obo.RO_0002216: {owl.ObjectProperty, obo.RO_0002500, obo.RO_0002328} => {obo.RO_0002500, obo.RO_0002328}
* Owlready * Reparenting obo.RO_0002264: {owl.ObjectProperty, obo.RO_0002500} => {obo.RO_0002500}
* Owlready * Reparenting obo.RO_0002516: {owl.ObjectProperty, obo.RO_0002524, owl.TransitiveProperty} => {obo.RO_0002524, obo.RO_0002525}
* Owlready * Reparenting obo.RO_0002517: {owl.ObjectProperty, obo.RO_0002524, owl.TransitiveProperty} => {obo.RO_0002524, obo.RO_0002525}
* Owlready * Reparenting property.AFX_0002731: {owl.ObjectProperty, property.AFX_0000388} => {property.AFX_0000388}
* Owlready * Reparenting property.AFX_0000557: {owl.ObjectProperty, property.AFX_0000331} => {property.AFX_0000331}
* Owlready * Reparenting property.AFX_0000558: {owl.ObjectProperty, property.AFX_0000331} => {property.AFX_0000331}
* Owlready * Reparenting obo.RO_0002331: {obo.RO_0002431, owl.ObjectProperty} => {obo.RO_0002431}
* Owlready * Reparenting property.AFX_0002686: {owl.ObjectProperty, property.AFX_0002718} => {property.AFX_0002718}
* Owlready * Reparenting property.AFX_0002836: {owl.ObjectProperty, property.AFX_0002834} => {property.AFX_0002834}
* Owlready * Reparenting obo.RO_0002085: {owl.ObjectProperty, obo.RO_0002088, owl.TransitiveProperty} => {obo.RO_0002088, owl.TransitiveProperty, obo.RO_0002084}
* Owlready * Reparenting property.AFX_0002745: {owl.ObjectProperty, obo.RO_0000057} => {obo.RO_0000057}
* Owlready * Reparenting property.AFX_0000399: {owl.ObjectProperty, obo.RO_0000057} => {obo.RO_0000057}
* Owlready * Reparenting obo.RO_0002505: {owl.ObjectProperty, obo.RO_0000057} => {obo.RO_0000057}
* Owlready * Reparenting property.AFX_0000395: {owl.ObjectProperty, obo.RO_0000057} => {obo.RO_0000057}
* Owlready * Reparenting obo.RO_0002332: {owl.ObjectProperty, obo.RO_0000057} => {obo.RO_0000057}
* Owlready * Reparenting obo.RO_0002218: {owl.ObjectProperty, obo.RO_0000057} => {obo.RO_0000057}
* Owlready * Reparenting property.AFX_0002750: {owl.ObjectProperty, obo.RO_0000057} => {obo.RO_0000057}
* Owlready * Reparenting obo.RO_0002526: {obo.RO_0002131, owl.ObjectProperty, obo.RO_0002514} => {obo.RO_0002131, obo.RO_0002514}
* Owlready * Reparenting obo.BFO_0000184: {owl.ObjectProperty, owl.InverseFunctionalProperty, obo.BFO_0000066} => {owl.InverseFunctionalProperty, obo.BFO_0000066}
* Owlready * Reparenting property.AFX_0000561: {owl.ObjectProperty, property.AFX_0000314} => {property.AFX_0000314}
* Owlready * Reparenting property.AFX_0000560: {owl.ObjectProperty, property.AFX_0000314} => {property.AFX_0000314}
* Owlready * Reparenting obo.RO_0002219: {owl.ObjectProperty, obo.RO_0002220} => {obo.RO_0002220}
* Owlready * Reparenting property.AFX_0002819: {owl.ObjectProperty, obo.IAO_0000219} => {obo.IAO_0000219}
* Owlready * Reparenting property.AFX_0002717: {owl.ObjectProperty, obo.IAO_0000219} => {obo.IAO_0000219}
* Owlready * Reparenting obo.RO_0002086: {owl.ObjectProperty, obo.RO_0002222, owl.TransitiveProperty} => {obo.RO_0002222, owl.TransitiveProperty}
* Owlready * Reparenting obo.BFO_0000117: {obo.RO_0002222, owl.ObjectProperty, obo.BFO_0000051, owl.TransitiveProperty} => {obo.BFO_0000051, obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002081: {owl.ObjectProperty, obo.RO_0002222} => {obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002230: {obo.RO_0002222, owl.ObjectProperty, obo.BFO_0000051, owl.TransitiveProperty} => {obo.BFO_0000051, obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002089: {owl.ObjectProperty, obo.RO_0002222, owl.TransitiveProperty} => {obo.RO_0002222, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002091: {owl.ObjectProperty, obo.RO_0002222} => {obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002084: {owl.ObjectProperty, obo.RO_0002222} => {obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002223: {owl.ObjectProperty, obo.RO_0002222, obo.BFO_0000050} => {obo.RO_0002222, obo.BFO_0000050}
* Owlready * Reparenting obo.RO_0002088: {owl.ObjectProperty, obo.RO_0002222} => {obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002229: {owl.ObjectProperty, obo.RO_0002222, obo.BFO_0000050} => {obo.RO_0002222, obo.BFO_0000050}
* Owlready * Reparenting obo.BFO_0000063: {owl.ObjectProperty, obo.RO_0002222, owl.TransitiveProperty} => {obo.RO_0002222, owl.TransitiveProperty}
* Owlready * Reparenting obo.BFO_0000062: {owl.ObjectProperty, obo.RO_0002086, owl.TransitiveProperty} => {obo.RO_0002086}
* Owlready * Reparenting property.AFX_0002816: {owl.ObjectProperty, property.AFX_0002699} => {property.AFX_0002699}
* Owlready * Reparenting property.AFX_0002835: {owl.ObjectProperty, property.AFX_0002833} => {property.AFX_0002833}
* Owlready * Reparenting obo.RO_0000052: {obo.RO_0002314, owl.ObjectProperty} => {obo.RO_0002314}
* Owlready * Reparenting obo.RO_0002518: {owl.ObjectProperty, obo.RO_0002524, owl.TransitiveProperty} => {obo.RO_0002524}
* Owlready * Reparenting core.broader: {core.broaderTransitive, owl.ObjectProperty} => {core.broaderTransitive}
* Owlready * Reparenting property.AFX_0000542: {owl.ObjectProperty, property.AFX_0000399} => {property.AFX_0000399}
* Owlready * Reparenting property.AFX_0000696: {owl.ObjectProperty, property.AFX_0000399} => {property.AFX_0000399}
* Owlready * Reparenting property.AFX_0002748: {owl.ObjectProperty, property.AFX_0000399} => {property.AFX_0000399}
* Owlready * Reparenting obo.RO_0002410: {obo.RO_0002609, owl.ObjectProperty} => {obo.RO_0002609}
* Owlready * Reparenting obo.RO_0002610: {obo.RO_0002609, owl.ObjectProperty} => {obo.RO_0002609}
* Owlready * Reparenting obo.RO_0002584: {owl.ObjectProperty, obo.RO_0002328, obo.RO_0002595} => {obo.RO_0002328, obo.RO_0002595}
* Owlready * Reparenting obo.RO_0002500: {owl.ObjectProperty, obo.RO_0002595} => {obo.RO_0002595}
* Owlready * Reparenting property.AFX_0000353: {owl.ObjectProperty, obo.RO_0000056} => {obo.RO_0000056}
* Owlready * Reparenting property.AFX_0002864: {owl.ObjectProperty, obo.RO_0000056} => {obo.RO_0000056}
* Owlready * Reparenting obo.RO_0002461: {owl.ObjectProperty, obo.RO_0000056} => {obo.RO_0000056}
* Owlready * Reparenting property.AFX_0002863: {owl.ObjectProperty, obo.RO_0000056} => {obo.RO_0000056}
* Owlready * Reparenting obo.RO_0002217: {owl.ObjectProperty, obo.RO_0000056} => {obo.RO_0000056}
* Owlready * Reparenting obo.RO_0002524: {owl.ObjectProperty, obo.BFO_0000051, owl.TransitiveProperty, obo.RO_0002522, obo.RO_0002526} => {obo.RO_0002526, obo.BFO_0000051, obo.RO_0002522}
* Owlready * Reparenting property.AFX_0002724: {owl.ObjectProperty, property.AFX_0002723} => {property.AFX_0002723}
* Owlready * Reparenting obo.RO_0002431: {owl.ObjectProperty, obo.RO_0002500, obo.RO_0002328, obo.RO_0002264} => {obo.RO_0002328, obo.RO_0002264}
* Owlready * Reparenting obo.RO_0002263: {owl.ObjectProperty, obo.RO_0002264} => {obo.RO_0002264}
* Owlready * Reparenting obo.RO_0002215: {owl.ObjectProperty, obo.RO_0002216} => {obo.RO_0002216}
* Owlready * Reparenting obo.RO_0002326: {owl.ObjectProperty, obo.RO_0002216} => {obo.RO_0002216}
* Owlready * Reparenting core.topConceptOf: {owl.ObjectProperty, core.inScheme} => {core.inScheme}
* Owlready * Reparenting property.AFX_0002690: {owl.ObjectProperty, property.AFX_0002684} => {property.AFX_0002684}
* Owlready * Reparenting property.AFX_0002718: {owl.ObjectProperty, property.AFX_0002684} => {property.AFX_0002684}
* Owlready * Reparenting obo.RO_0002336: {owl.ObjectProperty, obo.RO_0002334} => {obo.RO_0002334}
* Owlready * Reparenting obo.RO_0002335: {owl.ObjectProperty, obo.RO_0002334} => {obo.RO_0002334}
* Owlready * Reparenting obo.RO_0002559: {owl.ObjectProperty, obo.RO_0002506} => {obo.RO_0002506}
* Owlready * Reparenting obo.RO_0002509: {obo.RO_0002131, owl.ObjectProperty, obo.RO_0002506} => {obo.RO_0002131, obo.RO_0002506}
* Owlready * Reparenting obo.OBI_0000314: {owl.ObjectProperty, property.AFX_0002821} => {property.AFX_0002821}
* Owlready * Reparenting obo.RO_0002344: {owl.ObjectProperty, obo.RO_0002337} => {obo.RO_0002337}
* Owlready * Reparenting obo.RO_0002341: {owl.ObjectProperty, obo.RO_0002337} => {obo.RO_0002337}
* Owlready * Reparenting obo.BFO_0000051: {obo.RO_0002131, owl.ObjectProperty, owl.TransitiveProperty} => {obo.RO_0002131, owl.TransitiveProperty}
* Owlready * Reparenting obo.BFO_0000050: {obo.RO_0002131, owl.ObjectProperty, owl.TransitiveProperty} => {obo.RO_0002131, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002570: {obo.RO_0002131, owl.ObjectProperty} => {obo.RO_0002131}
* Owlready * Reparenting obo.RO_0002379: {obo.RO_0002131, owl.ObjectProperty} => {obo.RO_0002131}
* Owlready * Reparenting property.AFX_0002878: {property.AFX_0002730, owl.ObjectProperty} => {property.AFX_0002730}
* Owlready * Reparenting obo.RXNO_0000423: {owl.ObjectProperty, obo.BFO_0000077} => {obo.BFO_0000077}
* Owlready * Reparenting obo.RO_0002525: {obo.BFO_0000050, owl.ObjectProperty, obo.RO_0002523, owl.TransitiveProperty, obo.RO_0002526} => {obo.RO_0002526, obo.RO_0002523, obo.BFO_0000050}
* Owlready * Reparenting obo.RO_0002427: {obo.RO_0002501, owl.ObjectProperty, owl.TransitiveProperty} => {obo.RO_0002501}
* Owlready * Reparenting property.AFX_0002699: {owl.ObjectProperty, obo.IAO_0000136} => {obo.IAO_0000136}
* Owlready * Reparenting property.AFX_0002704: {owl.ObjectProperty, obo.IAO_0000136} => {obo.IAO_0000136}
* Owlready * Reparenting property.AFX_0000388: {owl.ObjectProperty, obo.IAO_0000136} => {obo.IAO_0000136}
* Owlready * Reparenting property.AFX_0002842: {owl.ObjectProperty, obo.IAO_0000136} => {obo.IAO_0000136}
* Owlready * Reparenting property.AFX_0002806: {owl.ObjectProperty, obo.IAO_0000136} => {obo.IAO_0000136}
* Owlready * Reparenting obo.IAO_0000219: {owl.ObjectProperty, obo.IAO_0000136} => {obo.IAO_0000136}
* Owlready * Reparenting property.AFX_0002725: {owl.ObjectProperty, property.AFX_0002722} => {property.AFX_0002722}
* Owlready * Reparenting obo.BFO_0000077: {owl.ObjectProperty, obo.BFO_0000057} => {obo.BFO_0000057}
* Owlready * Reparenting obo.RO_0002607: {owl.ObjectProperty, obo.RO_0002610} => {obo.RO_0002610}
* Owlready * Reparenting obo.RO_0002503: {obo.RO_0002502, owl.ObjectProperty} => {obo.RO_0002502}
* Owlready * Reparenting obo.RO_0002314: {obo.RO_0002502, owl.ObjectProperty} => {obo.RO_0002502}
* Owlready * Reparenting obo.RO_0000087: {owl.ObjectProperty, obo.RO_0000053} => {obo.RO_0000053}
* Owlready * Reparenting obo.RO_0002092: {owl.ObjectProperty, obo.RO_0002093, owl.TransitiveProperty} => {obo.RO_0002093, obo.RO_0002091, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002180: {owl.ObjectProperty, obo.BFO_0000051} => {obo.BFO_0000051}
* Owlready * Reparenting property.AFX_0000940: {owl.ObjectProperty, obo.BFO_0000051} => {obo.BFO_0000051}
* Owlready * Reparenting obo.RO_0002012: {owl.ObjectProperty, obo.RO_0002418, obo.BFO_0000050} => {obo.RO_0002418, obo.BFO_0000050}
* Owlready * Reparenting obo.RO_0002211: {owl.ObjectProperty, obo.RO_0002418} => {obo.RO_0002418}
* Owlready * Reparenting obo.RO_0002501: {owl.ObjectProperty, owl.TransitiveProperty, obo.RO_0002410} => {owl.TransitiveProperty, obo.RO_0002410}
* Owlready * Reparenting obo.RO_0002595: {owl.ObjectProperty, obo.RO_0002410} => {obo.RO_0002410}
* Owlready * Reparenting obo.RO_0002506: {owl.ObjectProperty, obo.RO_0002410} => {obo.RO_0002410}
* Owlready * Reparenting obo.RO_0003302: {owl.ObjectProperty, obo.RO_0002410} => {obo.RO_0002410}
* Owlready * Reparenting property.AFX_0002800: {owl.ObjectProperty, owl.TransitiveProperty, property.AFX_0002846} => {property.AFX_0002846}
* Owlready * Reparenting obo.BFO_0000139: {owl.ObjectProperty, owl.TransitiveProperty, obo.BFO_0000132} => {obo.BFO_0000132}
* Owlready * Reparenting obo.RO_0003304: {owl.ObjectProperty, obo.RO_0003302} => {obo.RO_0003302}
* Owlready * Reparenting obo.RO_0003303: {owl.ObjectProperty, obo.RO_0003302} => {obo.RO_0003302}
* Owlready * Reparenting property.AFX_0002846: {owl.ObjectProperty, obo.BFO_0000050} => {obo.BFO_0000050}
* Owlready * Reparenting property.AFX_0002687: {property.AFX_0002686, owl.ObjectProperty} => {property.AFX_0002686}
* Owlready * Reparenting property.AFX_0002688: {property.AFX_0002686, owl.ObjectProperty} => {property.AFX_0002686}
* Owlready * Reparenting property.AFX_0002689: {property.AFX_0002686, owl.ObjectProperty} => {property.AFX_0002686}
* Owlready * Reparenting property.AFX_0000072: {property.AFX_0002686, owl.ObjectProperty} => {property.AFX_0002686}
* Owlready * Reparenting core.broaderTransitive: {owl.ObjectProperty, owl.TransitiveProperty, core.semanticRelation} => {owl.TransitiveProperty, core.semanticRelation}
* Owlready * Reparenting core.mappingRelation: {owl.ObjectProperty, core.semanticRelation} => {core.semanticRelation}
* Owlready * Reparenting obo.RO_0002333: {owl.ObjectProperty, obo.RO_0002328} => {obo.RO_0002328}
* Owlready * Reparenting obo.RO_0002087: {obo.BFO_0000062, owl.ObjectProperty} => {obo.BFO_0000062}
* Owlready * Reparenting property.AFX_0002696: {owl.ObjectProperty, property.AFX_0002803} => {property.AFX_0002803}
* Owlready * Reparenting property.AFX_0002801: {owl.ObjectProperty, property.AFX_0002803} => {property.AFX_0002803}
* Owlready * Reparenting property.AFX_0001049: {owl.ObjectProperty, obo.RO_0001025} => {obo.RO_0001025}
* Owlready * Reparenting property.AFX_0002838: {owl.ObjectProperty, property.AFX_0002837} => {property.AFX_0002837}
* Owlready * Reparenting property.AFX_0002839: {owl.ObjectProperty, property.AFX_0002837} => {property.AFX_0002837}
* Owlready * Reparenting obo.RO_0002083: {owl.ObjectProperty, owl.TransitiveProperty, obo.RO_0002081} => {owl.TransitiveProperty, obo.RO_0002081}
* Owlready * Reparenting obo.RO_0002082: {owl.ObjectProperty, owl.TransitiveProperty, obo.RO_0002081} => {owl.TransitiveProperty, obo.RO_0002081}
* Owlready * Reparenting obo.RO_0002176: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002170: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002163: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002000: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002150: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002177: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002131: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting property.AFX_0002862: {property.AFX_0000675, owl.DatatypeProperty} => {property.AFX_0000675}
* Owlready * Reparenting property.AFX_0001198: {property.AFX_0000604, owl.DatatypeProperty} => {property.AFX_0000604}
* Owlready * Reparenting property.AFX_0002861: {property.AFX_0000671, owl.DatatypeProperty} => {property.AFX_0000671}
* Owlready * Reparenting property.AFX_0001732: {property.AFX_0000690, owl.DatatypeProperty} => {property.AFX_0000690}
* Owlready * Reparenting property.AFX_0000675: {property.AFX_0000674, owl.DatatypeProperty} => {property.AFX_0000674}
* Owlready * Reparenting property.AFX_0000676: {property.AFX_0000674, owl.DatatypeProperty} => {property.AFX_0000674}

The afo_dataset-1-2024-03-05 ontology consists of following publications:

,DOI,Title
0,10.1016/0304-5102(93)87113-m,Vapour phase propene hydroformylation catalyzed by the Rh/Al system on silica
1,10.1021/acscatal.0c04684.s001,Promotion of Inorganic Phosphorus on Rh Catalysts in Styrene Hydroformylation: Geometric and Electronic Effects
2,10.1021/acscatal.1c00705.s002,Theoretical Study of Ethylene Hydroformylation on Atomically Dispersed Rh/Al2O3 Catalysts: Reaction Mechanism and Influence of the ReOx Promoter
3,10.1021/acscatal.1c02014.s001,Activity Promotion of Rh8xCoxP4 Bimetallic Phosphides in Styrene Hydroformylation: Dual Influence of Adsorption and Surface Reaction
4,10.1021/acscatal.1c04359,Comparison of Heterogeneous Hydroformylation of Ethylene and Propylene over RhCo3/MCM-41 Catalysts
5,10.1021/acscatal.7b00499.s001,Platinum Group Metal Phosphides as Heterogeneous Catalysts for the Gas-Phase Hydroformylation of Small Olefins
6,10.1021/jacs.1c09665.s001,Intermetallic Nanocatalyst for Highly Active Heterogeneous Hydroformylation
7,10.1016/j.apcata.2018.02.019,Rhodium incorporated monometallic cobalt hydrotalcite-type materials: Preparation and its applications for the hydroformylation of alkenes
8,10.1021/jacs.2c11075.s001,Ethene Hydroformylation Catalyzed by Rhodium Dispersed with Zinc or Cobalt in Silanol Nests of Dealuminated Zeolite Beta
9,10.1016/s0920-5861(00)00261-3,Ethylene hydroformylation and carbon monoxide hydrogenation over modified and unmodified silica supported rhodium catalysts
10,10.1016/j.apcata.2013.10.019,Experimental investigation of ethylene hydroformylation to propanal on Rh and Co based catalysts
11,10.1016/s1381-1169(97)00035-6,Formation of bimetallic RhCo3 clusters from monometallic carbonyl clusters on SiO2 as probed by hydroformylation
12,10.1021/acs.iecr.0c03437.s001,Insights into the Bimetallic Effects of a RhCo Catalyst for Ethene Hydroformylation: Experimental and DFT Investigations
13,10.1021/acs.iecr.9b03598.s001,Heterogeneous Ligand-Free Rhodium Oxide Catalyst Embedded within Zeolitic Microchannel to Enhance Regioselectivity in Hydroformylation
14,10.1021/acsami.0c21749.s001,Effectively Regulating the Microenvironment of Atomically Dispersed Rh through Co and Pi to Promote the Selectivity in Olefin Hydroformylation
15,10.1021/acsanm.1c02194.s001,Rh2P Nanoparticles Stabilized by Carbon Patches for Hydroformylation of Olefins
16,10.1038/s41586-022-05075-4,Bifunctional hydroformylation on heterogeneous Rh-WOx pair site catalysts
17,10.1016/1381-1169(96)00243-9,Highly selective vapor phase propene hydroformylation catalyzed by RhB and RhCoB systems on silica
18,10.1021/acscatal.9b02111.s001,Synthesis of Heteroatom RhReOx Atomically Dispersed Species on Al2O3 and Their Tunable Catalytic Reactivity in Ethylene Hydroformylation

define DOI if only publications similar to specific publication in ontology should be queried from scopus\
if all publications in ontology should be used for query define the variable as:\
`doi = None`

In [3]:
doi = r'10.1021/acscatal.1c00705.s002'

Retrieve an abstract of the specific publication in the ontology given the DOI of the publication

In [23]:
doi_1=r'10.1021/acscatal.1c00705.s002'
abstract=get_abstr(doi_1)

Abstract: Atomically dispersed late transition-metal catalysts on supports have demonstrated unexpectedly high activity and selectivity compared to metal clusters, attributed to the unique electronic properties determined by the metal−support interface and the presence of promoters that modify the local environment of the single-atom site. Through cooperativity and synergism, these structures provide a fertile ground for catalyst discovery. Understanding these materials at the atomic scale and how to tune their electronic properties will be key for designing novel catalysts for selective chemistries. Here, we use density functional theory calculations and ﬁrst-principles microkinetic modeling to unveil extensive mechanistic knowledge about the cooperativity of atomically dispersed Rh−ReOx pairs on the γ-alumina support for the hydroformylation of ethylene to propanal. By considering a number of possible pre-catalyst complexes, we conﬁrm that the most stable one is a Rh gem-dicarbonyl species, Rh(CO)2, which, contrary to the homogeneous Wilkinson complex, assumes a 16-electron square-planar geometry by coordinating to two alumina surface oxygen atoms. We ﬁnd the weakening of the Rh−CO coordinative bonds with increasing ReOx loading, conﬁrming an earlier experimental work. We develop mechanisms for two competing reactions, ethylene hydroformylation and hydrogenation, and show that they reproduce experimental observations and trends such as reaction kinetics and, most critically, the increase in hydroformylation selectivity in the presence of ReOx. In these mechanisms, the catalyst is activated by the dissociation of one of the two CO ligands of Rh(CO)2 to allow ethylene and H2 coordination, in that order, and we provide evidence that H2 dissociation on Rh is not oxidative. We determine the hydroformylation rate-limiting step and show that it depends on the local environment of Rh: in the absence of ReOx, the hydroformylation is controlled by the acylation step and requires octahedrally coordinated Rh, namely, re-binding of a CO ligand prior to the acylation; in the presence of ReOx, and owing to the weakening of the Rh−CO bonds, the requisite CO coordination prior to the insertion step becomes rate-controlling. We assert that ReOx steers the reaction toward propanal by impeding a critical rearrangement of the Rh ligands that favors the competing reaction, ethylene hydrogenation. KEYWORDS: hydroformylation, density-functional theory, single-atom catalysis, rhodium, heterogeneous, γ-alumina

Following cells represent possible queries for reactions

- get list of all reactions for corresponding doi or from all publications if doi=None

In [24]:
list_reac_doi,_ = get_reaction(reac=None,doi=doi,include_all=False) #doi=None (if from all publications)
reac_all = [*set([i[0].lower() for i in list_reac_doi])]
print(reac_all)

['hydroformylation', 'atmospheric hydroformylation', 'heterogeneous hydroformylation', 'gas-phase hydroformylation', 'acylation', 'decarbonylation', 'dissociation', 'hydrogenation']

- get the list of all publications in ontology where same reactions as in input publication were mentioned

In [6]:
list_reac_doi,_ = get_reaction(reac = None,doi = doi) #get list of all reactions mentioned in given doi (doi should be part of ontology)
same_reac_doi = []
for i in list_reac_doi:
    reac_doi,_ = get_reaction(reac = i[0],doi = None)
    for c in reac_doi:
        if c not in same_reac_doi and c[0] != doi:
            same_reac_doi.append(c)     #output example: [['10.1016/0304-5102(93)87113-m'],['10.1016/1381-1169(96)00243-9']]

print(list_reac_doi)
print(same_reac_doi)

[['hydroformylation'], ['hydrogenation'], ['acylation']]
[['10.1016/0304-5102(93)87113-m'], ['10.1021/acscatal.0c04684.s001'], ['10.1021/acscatal.1c02014.s001'], ['10.1021/acscatal.1c04359'], ['10.1021/acscatal.7b00499.s001'], ['10.1021/acscatal.9b02111.s001'], ['10.1021/jacs.1c09665.s001'], ['10.1016/j.apcata.2018.02.019'], ['10.1021/jacs.2c11075.s001'], ['10.1016/1381-1169(96)00243-9'], ['10.1016/s0920-5861(00)00261-3'], ['10.1016/j.apcata.2013.10.019'], ['10.1016/s1381-1169(97)00035-6'], ['10.1021/acs.iecr.0c03437.s001'], ['10.1021/acs.iecr.9b03598.s001'], ['10.1021/acsami.0c21749.s001'], ['10.1038/s41586-022-05075-4']]

- get the list of publications, that mention the specific reaction

In [7]:
reac="hydrogenation"
list_reac_doi,_ = get_reaction(reac=reac,doi=None)  #output example: [['10.1016/0304-5102(93)87113-m'],['10.1016/1381-1169(96)00243-9']]
print(list_reac_doi)

[['10.1021/acscatal.0c04684.s001'], ['10.1021/acscatal.1c00705.s002'], ['10.1021/acscatal.1c04359'], ['10.1021/jacs.2c11075.s001'], ['10.1016/s0920-5861(00)00261-3'], ['10.1016/j.apcata.2013.10.019']]

- get list of all publications which mention the specific reaction and reactions which have this specific reaction as part of their label

In [8]:
reac="hydroformylation" #specify a reaction

list_reac_doi, df_reac = get_reaction(reac="hydroformylation",doi=None, include_all=True)

display(df_reac)

                              DOI                           Title
0    10.1016/0304-5102(93)87113-m                hydroformylation
1   10.1021/acscatal.0c04684.s001                hydroformylation
2   10.1021/acscatal.1c00705.s002                hydroformylation
3   10.1021/acscatal.1c02014.s001                hydroformylation
4        10.1021/acscatal.1c04359                hydroformylation
5   10.1021/acscatal.7b00499.s001                hydroformylation
6   10.1021/acscatal.9b02111.s001                hydroformylation
7       10.1021/jacs.1c09665.s001                hydroformylation
8    10.1016/j.apcata.2018.02.019                hydroformylation
9       10.1021/jacs.2c11075.s001                hydroformylation
10   10.1016/1381-1169(96)00243-9                hydroformylation
11  10.1016/s0920-5861(00)00261-3                hydroformylation
12   10.1016/j.apcata.2013.10.019                hydroformylation
13  10.1016/s1381-1169(97)00035-6                hydroformylation
14  10.1021/acs.iecr.0c03437.s001                hydroformylation
15  10.1021/acs.iecr.9b03598.s001                hydroformylation
16    10.1021/acsami.0c21749.s001                hydroformylation
17     10.1038/s41586-022-05075-4                hydroformylation
18   10.1016/1381-1169(96)00243-9    atmospheric hydroformylation
19  10.1021/acs.iecr.0c03437.s001      gas-phase hydroformylation
20       10.1021/acscatal.1c04359  heterogeneous hydroformylation
21      10.1021/jacs.1c09665.s001                Hydroformylation

- get list of all entities mentioned in specific publication

In [9]:
list_ent=get_entList(list_type='all',entity= None,doi=doi)
print([i[1] for i in list_ent])

['rhodium atom', 'hydroformylation', 'ethene', 'hydrogenation', 'oxygen atom', 'propanal', 'acylation', 'heterogeneous, γ-alumina', 'ReOx', 'rhenium atom', 'γ-alumina']

- get list of all extracted entities from publications in knowledge graph

In [10]:
list_ent=[i[1] for i in get_entList(list_type='all',entity= None,doi=None)]
list_distinct=[]
for i in list_ent:
    if i not in list_distinct:
        list_distinct.append(i)
print(list_distinct)

['rhodium atom', 'Rh supported on Al catalyst with rhodium nanocrystal', 'Rh supported on Al', 'Rh supported on B', 'Rh supported on SiO2 catalyst', '5%Rh supported on Al2O3', '0.5%Co-0.5%Rh supported on Al2O3', 'Rh catalyst', 'Rh-based bimetallic catalyst', 'ligand-free rhodium nanoparticle catalyst', 'Rh-based atomically dispersed catalyst', 'Rh supported on ZnO modiﬁed with Pi', 'Co-Rh-based heterogeneous catalyst', 'Rh-containing bimetallic catalyst', 'Rh-containing bimetallic site', 'aluminium atom', 'silicon dioxide', 'boron atom', 'aluminium oxide', 'zinc oxide', 'bimetallic SiO2-supported RhCo3 cluster catalyst', 'Rh7Co1P4 supported on SiO2', 'rhodium trichloride supported on silica with lithium aluminum hydride', 'RhCo3 supported on SiO2', 'Rh2P supported on silica', 'Rh8-xCoxP4 supported on SiO2 catalyst', 'Rh2P nanoparticle supported on SiO2 support material', '1%Co supported on Al2O3', 'lithium tetrahydroaluminate', 'propene', 'hydroformylation', 'vapour phase propene', 'ethene', 'atmospheric ethylene', 'oleﬁn', 'styrene', 'ethylene', 'alkene', 'gas-phase ethylene', 'trichlororhodium', 'aldehyde', 'atmospheric hydroformylation', 'linear aldehyde', 'carbon monoxide', 'methanol', 'molybdenum trioxide', 'titanium dioxide', 'divanadium pentaoxide', 'hydrogenation', 'phenylpropionyl', 'c2-oxygenate', 'organic oxygenate', 'dissociation', 'oxygen(2-);scandium(3+)', 'oxygen atom', 'scandium atom', 'manganese(2+);oxygen(2-)', 'manganese atom', 'ethane', 'propanal', 'propan-1-ol', 'cobalt atom', 'M = Co', 'Co-containing catalyst', 'decarbonylation', 'binary catalyst', 'monometallic catalyst', 'cobalt;rhodium', 'RhCo bimetallic catalyst', 'RhCo3 supported on MCM-41', 'oxygenate', 'gas-phase hydroformylation', '1-hexene', '1-octene', '1-decene', '1-dodecene', 'Rh2O3 supported on S-1', 'supported Rh2O3 supported on S-1 catalyst', 'Rh2O3 supported on S-1-II', 'S-1', 'oxygen(2-);rhodium(3+)', 'S-1-II', 'rhodium oxide', 'silicalite-1', 'zeolite', 'oxide', 'dealuminated BEA zeolite', 'phosphate ion', 'Rh2P NPs', 'Rh2P nanoparticle', 'Rh2P', 'Rh2P catalyst', 'phosphorus atom', 'SACs', 'rhodium phosphide', 'phosphide(3-)', 'bimetallic phosphide', 'acylation', 'heterogeneous, γ-alumina', 'ReOx', 'rhenium atom', 'γ-alumina', 'heterogeneous catalyst', 'Rh7Co1P4', 'Rh8-xCoxP4', 'heterogeneous hydroformylation', 'MCM-41', 'late-transition-metal catalyst', 'atomically dispersed catalyst', 'single atom catalyst', 'pair site catalyst', 'Hydroformylation', 'RhZn intermetallic nanoparticle', "Wilkinson's catalyst", 'pure Rh(111)', 'RhZn', 'zinc atom', 'Rh(111)', 'CoRh-HT', 'hydrogen atom', 'homogeneous binuclear organometallic catalysts9', 'supported metal catalyst', 'rhodium-tungsten oxide', 'supported, atomically dispersed rhodium-tungsten oxide (Rh-WOx) pair site catalyst', 'Rh-WOx', 'tungsten']

In [13]:
doi=None

With following code the retrieval if all reactants, products, support materials, catalysts is performed, which are mentioned in one specific publication or from all publication in extended ontology (if doi=None) 
with `get_synonyms` all possible synonyms of chemical entities will be retrieved.\
For example from "rhodium atom " class, synonyms such as "Rh", "rhodium", "45Rh" are retrieved

In [14]:
sup_list=get_support(sup=None,doi=doi)
_,sup_all=get_synonyms(sup_list)
print('all queried synonyms of support:')
print(list(sup_all.values()))

cat_list=get_catalyst(cat=None,doi=doi,include_all=True)
_,cat_all=get_synonyms(cat_list)
print('\nall queried synonyms of catalytic components:')
print(list(cat_all.values()))

reactant_list=get_entList('reactant',entity= None,doi=doi)
reactant_all,_=get_synonyms(reactant_list)
print('\nall queried synonyms of reactants:')
print(reactant_all)

product_list=get_entList('product',entity= None,doi=doi)
product_all,_=get_synonyms(product_list)
print('\nall queried synonyms of products:')
print(product_all)

cat_list_full=get_catalyst_full(doi = doi)
_,cat_full_all=get_synonyms(cat_list_full)
print('\nall queried catalyst entities:')
print(list(cat_full_all.values()))

all queried synonyms of support:
[[aluminium atom, 'Al'], [boron atom, 'B'], [Silica, amorphous, 'SiO2'], [aluminium oxide, 'Al2O3'], [oxido de cinc, 'ZnO'], [lithium tetrahydroaluminate, 'LiAlH4'], ['S-1'], ['oxygen(2-);rhodium(3', 'Rh2O3'], ['silicalite-1'], ['oxide'], [rhodium-tungsten oxide], ['Rh-WOx']]

all queried synonyms of catalytic components:
[[rhodium atom, 'Rh'], [Silica, amorphous, 'SiO2'], ['trichlororhodium'], [molybdenum trioxide, 'MoO3'], ['TiO2', dioxido de titanio], ['V2O5', divanadium pentaoxide], ['oxygen(2-);scandium(3', 'Sc2O3'], ['manganese(2+);oxygen(2-', 'Mn2O3'], [cobalt atom, 'Co'], [M = Co], ['cobalt;rhodium', 'RhCo'], ['S-1-II'], [rhodium oxide], ['zeolite'], [phosphate ion, 'Pi'], ['Rh2P'], [rhodium phosphide], ['phosphanetriide', 'P(-)'], [bimetallic phosphide], [], [heterogeneous, γ-alumina], ['ReOx'], ['Rh7Co1P4'], ['Rh8-xCoxP4'], ['MCM-41'], ['RhZn'], ['Rh(111)']]

all queried synonyms of reactants:
['prop-1-ene', 'R-1270', vapour phase propene, 'ethene', 'Styren', 'alkene', gas-phase ethylene, carbon monoxide, carbon monoxide, 'CO', 'phenylpropionyl', '1-hexene', 'alpha', '1-C8H16', '1-decene', hydrogen atom, 'H']

all queried synonyms of products:
['aldehidos', 'RC(=O)H', linear aldehyde, 'CH3OH', 'methanol', ethyl hydride, 'C2H6', 'Propanaldehyde', 'C2H5CHO', '1-Hydroxypropane', 'N-PROPANOL']

all queried catalyst entities:
[[Rh supported on Al catalyst with rhodium nanocrystal], [Rh supported on Al, 'Rh/Al'], [Rh supported on B, 'Rh/B'], [Rh supported on SiO2 catalyst], [5%Rh supported on Al2O3], [0.5%Co-0.5%Rh supported on Al2O3], [Rh catalyst], [Rh supported on ZnO modiﬁed with Pi], [Rh-containing bimetallic site], [Rh7Co1P4 supported on SiO2, 'Rh7Co1P4/SiO2'], [rhodium trichloride supported on silica with lithium aluminum hydride], [RhCo3 supported on SiO2, 'RhCo3/SiO2'], [Rh2P supported on silica], [Rh8-xCoxP4 supported on SiO2 catalyst], [Rh2P nanoparticle supported on SiO2 support material], [1%Co supported on Al2O3], [Co-containing catalyst], [RhCo3 supported on MCM-41, 'RhCo3/MCM-41'], [Rh2O3 supported on S-1, 'Rh2O3@S-1'], [supported Rh2O3 supported on S-1 catalyst], [Rh2O3 supported on S-1-II, 'Rh2O3@S-1-II'], ['zeolite'], [dealuminated BEA zeolite], [Rh2P NPs], [Rh2P nanoparticle], [Rh2P catalyst], [RhZn intermetallic nanoparticle], [pure Rh(111)], ['CoRh-HT', bimetallic cobalt-rhodium layered hydrotalcite-type material]]

In [15]:
sup_list=get_support(sup=None,doi=doi)
_,sup_all=get_synonyms(sup_list)
print('all queried synonyms of support:')
print(list(sup_all.values()))

all queried synonyms of support:
[[aluminium atom, 'Al'], [boron atom, 'B'], [Silica, amorphous, 'SiO2'], [aluminium oxide, 'Al2O3'], [oxido de cinc, 'ZnO'], [lithium tetrahydroaluminate, 'LiAlH4'], ['S-1'], ['oxygen(2-);rhodium(3', 'Rh2O3'], ['silicalite-1'], ['oxide'], [rhodium-tungsten oxide], ['Rh-WOx']]

In [16]:
onto_pub_list

[['10.1016/0304-5102(93)87113-m',
  'Vapour phase propene hydroformylation catalyzed by the Rh/Al system on silica'],
 ['10.1021/acscatal.0c04684.s001',
  'Promotion of Inorganic Phosphorus on Rh Catalysts in Styrene Hydroformylation: Geometric and Electronic Effects'],
 ['10.1021/acscatal.1c00705.s002',
  'Theoretical Study of Ethylene Hydroformylation on Atomically Dispersed Rh/Al2O3 Catalysts: Reaction Mechanism and Influence of the ReOx Promoter'],
 ['10.1021/acscatal.1c02014.s001',
  'Activity Promotion of Rh8xCoxP4 Bimetallic Phosphides in Styrene Hydroformylation: Dual Influence of Adsorption and Surface Reaction'],
 ['10.1021/acscatal.1c04359',
  'Comparison of Heterogeneous Hydroformylation of Ethylene and Propylene over RhCo3/MCM-41 Catalysts'],
 ['10.1021/acscatal.7b00499.s001',
  'Platinum Group Metal Phosphides as Heterogeneous Catalysts for the Gas-Phase Hydroformylation of Small Olefins'],
 ['10.1021/jacs.1c09665.s001',
  'Intermetallic Nanocatalyst for Highly Active Heterogeneous Hydroformylation'],
 ['10.1016/j.apcata.2018.02.019',
  'Rhodium incorporated monometallic cobalt hydrotalcite-type materials: Preparation and its applications for the hydroformylation of alkenes'],
 ['10.1021/jacs.2c11075.s001',
  'Ethene Hydroformylation Catalyzed by Rhodium Dispersed with Zinc or Cobalt in Silanol Nests of Dealuminated Zeolite Beta'],
 ['10.1016/s0920-5861(00)00261-3',
  'Ethylene hydroformylation and carbon monoxide hydrogenation over modified and unmodified silica supported rhodium catalysts'],
 ['10.1016/j.apcata.2013.10.019',
  'Experimental investigation of ethylene hydroformylation to propanal on Rh and Co based catalysts'],
 ['10.1016/s1381-1169(97)00035-6',
  'Formation of bimetallic RhCo3 clusters from monometallic carbonyl clusters on SiO2 as probed by hydroformylation'],
 ['10.1021/acs.iecr.0c03437.s001',
  'Insights into the Bimetallic Effects of a RhCo Catalyst for Ethene Hydroformylation: Experimental and DFT Investigations'],
 ['10.1021/acs.iecr.9b03598.s001',
  'Heterogeneous Ligand-Free Rhodium Oxide Catalyst Embedded within Zeolitic Microchannel to Enhance Regioselectivity in Hydroformylation'],
 ['10.1021/acsami.0c21749.s001',
  'Effectively Regulating the Microenvironment of Atomically Dispersed Rh through Co and Pi to Promote the Selectivity in Olefin Hydroformylation'],
 ['10.1021/acsanm.1c02194.s001',
  'Rh2P Nanoparticles Stabilized by Carbon Patches for Hydroformylation of Olefins'],
 ['10.1038/s41586-022-05075-4',
  'Bifunctional hydroformylation on heterogeneous Rh-WOx pair site catalysts'],
 ['10.1016/1381-1169(96)00243-9',
  'Highly selective vapor phase propene hydroformylation catalyzed by RhB and Rh\ue5f8CoB systems on silica'],
 ['10.1021/acscatal.9b02111.s001',
  'Synthesis of Heteroatom RhReOx Atomically Dispersed Species on Al2O3 and Their Tunable Catalytic Reactivity in Ethylene Hydroformylation']]

In [17]:
sup_list=get_support(sup=None,doi=doi,only_doi= False)
sup_cat=[]
for i in range(len(sup_list)):
    sup_cat.append([sup_list[i][1],sup_list[i][2]])
print(sup_cat)

[['aluminium atom', 'Rh supported on Al catalyst with rhodium nanocrystal'], ['aluminium atom', 'Rh supported on Al'], ['boron atom', 'Rh supported on B'], ['silicon dioxide', 'Rh supported on SiO2 catalyst'], ['silicon dioxide', 'Rh supported on SiO2 catalyst'], ['silicon dioxide', 'Rh supported on SiO2 catalyst'], ['silicon dioxide', 'Rh supported on SiO2 catalyst'], ['silicon dioxide', 'Rh supported on SiO2 catalyst'], ['silicon dioxide', 'Rh supported on SiO2 catalyst'], ['aluminium oxide', '5%Rh supported on Al2O3'], ['aluminium oxide', '0.5%Co-0.5%Rh supported on Al2O3'], ['zinc oxide', 'Rh supported on ZnO modiﬁed with Pi'], ['silicon dioxide', 'bimetallic SiO2-supported RhCo3 cluster catalyst'], ['silicon dioxide', 'bimetallic SiO2-supported RhCo3 cluster catalyst'], ['silicon dioxide', 'bimetallic SiO2-supported RhCo3 cluster catalyst'], ['silicon dioxide', 'bimetallic SiO2-supported RhCo3 cluster catalyst'], ['silicon dioxide', 'bimetallic SiO2-supported RhCo3 cluster catalyst'], ['silicon dioxide', 'bimetallic SiO2-supported RhCo3 cluster catalyst'], ['silicon dioxide', 'Rh7Co1P4 supported on SiO2'], ['silicon dioxide', 'Rh7Co1P4 supported on SiO2'], ['silicon dioxide', 'Rh7Co1P4 supported on SiO2'], ['silicon dioxide', 'Rh7Co1P4 supported on SiO2'], ['silicon dioxide', 'Rh7Co1P4 supported on SiO2'], ['silicon dioxide', 'Rh7Co1P4 supported on SiO2'], ['silicon dioxide', 'rhodium trichloride supported on silica with lithium aluminum hydride'], ['silicon dioxide', 'rhodium trichloride supported on silica with lithium aluminum hydride'], ['silicon dioxide', 'rhodium trichloride supported on silica with lithium aluminum hydride'], ['silicon dioxide', 'rhodium trichloride supported on silica with lithium aluminum hydride'], ['silicon dioxide', 'rhodium trichloride supported on silica with lithium aluminum hydride'], ['silicon dioxide', 'rhodium trichloride supported on silica with lithium aluminum hydride'], ['lithium tetrahydroaluminate', 'rhodium trichloride supported on silica with lithium aluminum hydride'], ['silicon dioxide', 'RhCo3 supported on SiO2'], ['silicon dioxide', 'RhCo3 supported on SiO2'], ['silicon dioxide', 'RhCo3 supported on SiO2'], ['silicon dioxide', 'RhCo3 supported on SiO2'], ['silicon dioxide', 'RhCo3 supported on SiO2'], ['silicon dioxide', 'RhCo3 supported on SiO2'], ['silicon dioxide', 'Rh2P supported on silica'], ['silicon dioxide', 'Rh2P supported on silica'], ['silicon dioxide', 'Rh2P supported on silica'], ['silicon dioxide', 'Rh2P supported on silica'], ['silicon dioxide', 'Rh2P supported on silica'], ['silicon dioxide', 'Rh2P supported on silica'], ['silicon dioxide', 'Rh8-xCoxP4 supported on SiO2 catalyst'], ['silicon dioxide', 'Rh8-xCoxP4 supported on SiO2 catalyst'], ['silicon dioxide', 'Rh8-xCoxP4 supported on SiO2 catalyst'], ['silicon dioxide', 'Rh8-xCoxP4 supported on SiO2 catalyst'], ['silicon dioxide', 'Rh8-xCoxP4 supported on SiO2 catalyst'], ['silicon dioxide', 'Rh8-xCoxP4 supported on SiO2 catalyst'], ['silicon dioxide', 'Rh2P nanoparticle supported on SiO2 support material'], ['silicon dioxide', 'Rh2P nanoparticle supported on SiO2 support material'], ['silicon dioxide', 'Rh2P nanoparticle supported on SiO2 support material'], ['silicon dioxide', 'Rh2P nanoparticle supported on SiO2 support material'], ['silicon dioxide', 'Rh2P nanoparticle supported on SiO2 support material'], ['silicon dioxide', 'Rh2P nanoparticle supported on SiO2 support material'], ['aluminium oxide', '1%Co supported on Al2O3'], ['S-1', 'Rh2O3 supported on S-1'], ['oxygen(2-);rhodium(3+)', 'Rh2O3 supported on S-1'], ['S-1', 'supported Rh2O3 supported on S-1 catalyst'], ['oxygen(2-);rhodium(3+)', 'supported Rh2O3 supported on S-1 catalyst'], ['oxygen(2-);rhodium(3+)', 'Rh2O3 supported on S-1-II'], ['S-1', 'rhodium oxide'], ['silicalite-1', 'rhodium oxide'], ['rhodium-tungsten oxide', 'supported, atomically dispersed rhodium-tungsten oxide (Rh-WOx) pair site catalyst'], ['Rh-WOx', 'supported, atomically dispersed rhodium-tungsten oxide (Rh-WOx) pair site catalyst']]

Perform a search in scopus using collected information from ontology\
Queries have following structure: 'TITLE-ABS-KEY("reaction"AND"catalyst"AND"support material"AND"reactant"AND"product")' in all possible combinations

In [22]:
doi=None
df_all=scopus_seach_process(doi, onto_pub_list)

processing publication #1
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Rh supported on Al catalyst with rhodium nanocrystal"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Rh supported on Al"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Rh/Al"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Rh supported on B"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Rh/B"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"rhodium trichloride supported on silica with lithium aluminum hydride"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"rhodium atom"AND"aluminium atom"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"rhodium atom"AND"Al"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Rh"AND"aluminium atom"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Rh"AND"Al"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"rhodium atom"AND"Silica, amorphous"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"rhodium atom"AND"SiO2"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Rh"AND"Silica, amorphous"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Rh"AND"SiO2"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"rhodium atom"AND"boron atom"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"rhodium atom"AND"B"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Rh"AND"boron atom"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Rh"AND"B"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"rhodium atom"AND"lithium tetrahydroaluminate"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"rhodium atom"AND"LiAlH4"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Rh"AND"lithium tetrahydroaluminate"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Rh"AND"LiAlH4"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Silica, amorphous"AND"aluminium atom"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Silica, amorphous"AND"Al"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"SiO2"AND"aluminium atom"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"SiO2"AND"Al"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Silica, amorphous"AND"boron atom"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Silica, amorphous"AND"B"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"SiO2"AND"boron atom"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"SiO2"AND"B"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Silica, amorphous"AND"lithium tetrahydroaluminate"AND"prop-1-ene"AND" ")
Downloading results for query TITLE-ABS-KEY("hydroformylation"AND"Silica, amorphous"AND"LiAlH4"AND"prop-1-ene"AND" ")

KeyboardInterrupt:

All distinct results are saved in sheet 'distinct_eid'.\
Filter found publication according to the start and end date\
If no filtering nessesary define `start_date` as follows:\
`get_synonyms = None`

In [ ]:
start_date = '2019-01-01'
end_date = '2023-12-31' 

distinct_df, filtered_df, filtered_df_doi, filtered_df_doi_new = filter_date(start_date,end_date, df_all,onto_pub_list)

save from scopus quieried publication information in Excel

In [ ]:
output_path='./output/output_new_23023024.xlsx' #define the output path

save_in_excel(output_path, df_all, distinct_df, filtered_df, filtered_df_doi, filtered_df_doi_new )